// Traduction des textes produits en français par le moteur de calcul (titres et formules des vérifications, libellés
// des éléments et des familles, solutions de calage, messages) pour le rapport en allemand ou en anglais. Table de
// correspondances : motifs d'abord (numéros d'angle, de tronçon…), puis expressions de la plus longue à la plus
// courte, enfin la typographie (guillemets, espace avant « : » et « ; ») et la virgule décimale en anglais.
// Les termes allemands suivent les notes statico. Fonction pure.
import type { Lang } from './i18n';

type Rule = readonly [string | RegExp, string, string];

/** Motifs (appliqués dans l'ordre). */
const PATTERNS: Rule[] = [
  [/grand côté (\d)/g, 'Längsseite $1', 'long side $1'],
  [/petit côté (\d)/g, 'Stirnseite $1', 'short side $1'],
  [/, tronçon (\d+)/g, ', Abschnitt $1', ', span $1'],
  [/angle (\d+), plancher/g, 'Ecke $1, Boden', 'corner $1, floor'],
  [/angle (\d+), toiture/g, 'Ecke $1, Dach', 'corner $1, roof'],
  [/liaison d’angle (\d+)/g, 'Eckverbindung $1', 'corner link $1'],
  [/\(([\d,]+) plat\)/g, '($1 Lasche)', '($1 plate)'],
  [/([\d,]+) plat\(s\)/g, '$1 Lasche(n)', '$1 plate(s)'],
  [/vérin d’angle (\d+)/g, 'Spindelfuß Ecke $1', 'corner jack $1'],
  [/vérin central (\d+)/g, 'Spindelfuß Mitte $1', 'middle jack $1'],
  [/Vérin Tr (\d+) × 5/g, 'Spindelfuß Tr $1 × 5', 'Jack Tr $1 × 5'],
  [/ : sortie ([\d,]+) cm > ([\d,]+) cm autorisés/g, ': Auszug $1 cm > $2 cm zulässig', ': extension $1 cm > $2 cm allowed'],
  [/(\d) angles sur une plaque/g, '$1 Ecken auf einer Unterpallung', '$1 corners on one plate'],
  [/groupe de (\d) angles/g, 'Gruppe mit $1 Ecken', 'group of $1 corners'],
  [/\bclasse (\d)/g, 'Klasse $1', 'class $1'],
  [/ · plancher, ([xy]) = /g, ' · Boden, $1 = ', ' · floor, $1 = '],
  [/ · toiture, ([xy]) = /g, ' · Dach, $1 = ', ' · roof, $1 = '],
  [/\((\d+) plaques?\)/g, '($1 Platte(n))', '($1 plate(s))'],
  [/(\d+) plaques empilées \(plus de (\d+)\)/g, '$1 gestapelte Platten (mehr als $2)', '$1 stacked plates (more than $2)'],
  [/(\d+) appui\(s\) soulevé\(s\) \(cas ([^)]+)\)/g, '$1 abhebende(s) Auflager (LK $2)', '$1 support(s) lifting off (comb. $2)'],
  [/\(cas ([^)]+)\)/g, '(LK $1)', '(comb. $1)'],
  [/ — cas ([A-Z0-9.]+)/g, ' — LK $1', ' — comb. $1'],
  [/\bcas ([A-Z0-9.]+)/g, 'LK $1', 'comb. $1'],
  [/(\d+) vérification\(s\) bloquée\(s\)/g, '$1 blockierte(r) Nachweis(e)', '$1 blocked check(s)'],
  [/(\d+) pièce\(s\) porteuse\(s\)/g, '$1 tragende(s) Bauteil(e)', '$1 load-bearing part(s)'],
  [/(\d+) ddl d’extrémité de barre sans rigidité, stabilisés/g, '$1 Stabendfreiheitsgrad(e) ohne Steifigkeit, stabilisiert', '$1 member end DOF(s) without stiffness, stabilised'],
  [/(\d+) nœud\(s\) dont une rotation n’est retenue par aucune barre \(articulations\) : rotation stabilisée/g, '$1 Knoten mit von keinem Stab gehaltener Verdrehung (Gelenke): Verdrehung stabilisiert', '$1 node(s) with a rotation restrained by no member (hinges): rotation stabilised'],
  [/stock insuffisant : (\d+) pièces nécessaires, (\d+) disponibles/g, 'Lagerbestand unzureichend: $1 Stück erforderlich, $2 vorhanden', 'insufficient stock: $1 pieces needed, $2 available'],
  [/posée (\d+) mm plus bas que le haut de/g, '$1 mm tiefer modelliert als die Oberkante von', 'modelled $1 mm lower than the top of'],
  [/posée (\d+) mm plus haut que le haut de/g, '$1 mm höher modelliert als die Oberkante von', 'modelled $1 mm higher than the top of'],
  [/(\d+) kg par tôle : manutention mécanique/g, '$1 kg je Blech: maschinelle Handhabung', '$1 kg per plate: mechanical handling'],
  // modifications de l'étude (core/mods.ts describeMods)
  [/lest de ([\d  ]+) kg sur le plancher de ([\w-]+)/g, 'Ballast $1 kg auf dem Boden von $2', 'ballast of $1 kg on the floor of $2'],
  [/contreventement en croix \(plat 60 × 6 \+ ridoir\) sur ([\w-]+), /g, 'Kreuzverband (Flachstahl 60 × 6 + Spannschloss) an $1, ', 'cross bracing (flat 60 × 6 + turnbuckle) on $1, '],
  [/Viewbox ([\w-]+) ajoutée contre ([\w-]+), /g, 'Viewbox $1 an $2 angebaut, ', 'Viewbox $1 added against $2, '],
  [/Viewbox ([\w-]+) ajoutée au-dessus de ([\w-]+)/g, 'Viewbox $1 auf $2 aufgesetzt', 'Viewbox $1 added on top of $2'],
  [/surélévation de (\d+) cm sur poteaux /g, 'Aufständerung um $1 cm auf Stützen ', 'raised by $1 cm on posts '],
  [/plats d’empilement : (\d+) par grand côté et (\d+) par petit côté/g, 'Stapellaschen: $1 je Längsseite und $2 je Stirnseite', 'stacking plates: $1 per long side and $2 per short side'],
  [/hauteur des poteaux ([\d  ]+) mm/g, 'Stützenhöhe $1 mm', 'column height $1 mm'],
  [/plancher en contreplaqué de (\d+) mm/g, 'Boden aus Sperrholz $1 mm', 'plywood floor $1 mm'],
  [/capacité saisie ([\w-]+) ([\w_]+) = ([\d,  ]+) (kNm|kN)( par [^(]+)? \(non vérifiée\)/g, 'eingegebene Tragfähigkeit $1 $2 = $3 $4 (nicht geprüft)', 'capacity entered $1 $2 = $3 $4 (not verified)'],
  [/rives du plancher en acier (S\d+)/g, 'Bodenrandträger in Stahl $1', 'floor edge beams in steel $1'],
  [/rives de toiture en acier (S\d+)/g, 'Dachrandträger in Stahl $1', 'roof edge beams in steel $1'],
  [/traverses et lisses du plancher en acier (S\d+)/g, 'Bodennebenträger in Stahl $1', 'floor secondary beams in steel $1'],
  [/traverses et lisses de toiture en acier (S\d+)/g, 'Dachnebenträger in Stahl $1', 'roof secondary beams in steel $1'],
  [/poteaux en acier (S\d+)/g, 'Stützen in Stahl $1', 'columns in steel $1'],
  [/réceptions de pied d’angle en acier (S\d+)/g, 'Fußaufnahmen an den Ecken in Stahl $1', 'corner foot receptacles in steel $1'],
  [/réceptions de pied centrales en acier (S\d+)/g, 'mittlere Fußaufnahmen in Stahl $1', 'middle foot receptacles in steel $1'],
  // escaliers extérieurs (templates/stair.ts, assemble.ts, results.ts)
  [/latte de palier (\d+)/g, 'Podestbelag $1', 'landing bar $1'],
  [/attache du montant de palier (\d+)/g, 'Anschluss Podeststütze $1', 'landing post connection $1'],
  [/pied de montant de palier (\d+)/g, 'Fuß der Podeststütze $1', 'foot of landing post $1'],
  [/montant de palier (\d+)/g, 'Podeststütze $1', 'landing post $1'],
  [/attache du palier (\d+)/g, 'Podestanschluss $1', 'landing connection $1'],
  [/Escalier extérieur ([\w-]+) \(/g, 'Außentreppe $1 (', 'External stair $1 ('],
  [/palier à ([\d,]+) m du sol — kit relevé pour 3,08 m, volée recalculée à la même pente\./g, 'Podest $1 m über Gelände — Bausatz für 3,08 m aufgenommen, Treppenlauf mit gleicher Neigung neu berechnet.', 'landing $1 m above ground — kit surveyed for 3.08 m, flight recalculated at the same slope.'],
  [/aucun perçage de ([\w-]+) en face du palier — attaches placées à ([\d,]+) et ([\d,]+) m du coin \(perçages à faire sur site\)\./g, 'keine Bohrung von $1 gegenüber dem Podest — Anschlüsse bei $2 und $3 m von der Ecke (Bohrungen vor Ort herzustellen).', 'no drilling of $1 facing the landing — connections placed at $2 and $3 m from the corner (to be drilled on site).'],
  [/volée ([\d,]+) m², palier ([\d,]+) m² ; /g, 'Treppenlauf $1 m², Podest $2 m²; ', 'flight $1 m², landing $2 m²; '],
  [/ ; garde-corps ([\d,]+) kN\/m ; palier à ([\d,]+) m/g, '; Geländer $1 kN/m; Podest auf $2 m', '; railings $1 kN/m; landing at $2 m'],
  // plaques partagées, position des plaques, Prüfbuch (placement.ts, calage.ts, tuv.ts)
  [/(\d+) vérins d’angle sur une plaque/g, '$1 Eckspindeln auf einer Platte', '$1 corner jacks on one plate'],
  [/(\d+) vérins centraux sur une plaque/g, '$1 Mittelspindeln auf einer Platte', '$1 middle jacks on one plate'],
  [/(\d+) platines de vérin/g, '$1 Spindelfußplatten', '$1 jack base plates'],
  [/, à fleur \((\d+)\) ou centré \((\d+)\)/g, ', bündig ($1) oder mittig ($2)', ', flush ($1) or centred ($2)'],
  [
    /à fleur de la Viewbox : charge à ([\d,]+) cm du bord, la plaque ne répartit que sur ([\d,]+) cm de large de ce côté \(B’ = B − 2 e\)/g,
    'bündig mit der Viewbox: Last $1 cm vom Rand, die Platte verteilt auf dieser Seite nur über $2 cm Breite (B’ = B − 2 e)',
    'flush with the Viewbox: load $1 cm from the edge, the plate only spreads over $2 cm on that side (B’ = B − 2 e)',
  ],
  [
    /À fleur de la Viewbox, la plaque ne répartirait que sur (\d+) × (\d+) cm \(charge près du bord\) → ([^:]+) : plaque centrée sous l’appui, elle dépasse de (\d+) cm\./g,
    'Bündig mit der Viewbox würde die Platte nur über $1 × $2 cm verteilen (Last nahe am Rand) → $3: Platte mittig unter dem Auflager, Überstand $4 cm.',
    'Laid flush with the Viewbox, the plate would only spread over $1 × $2 cm (load close to the edge) → $3: plate centred under the support, overhang $4 cm.',
  ],
  [/→ Centrer la plaque sous l’appui \(elle dépasse alors de (\d+) cm\) : ([^,]+), OK\./g, '→ Platte mittig unter das Auflager legen (Überstand $1 cm): $2, OK.', '→ Centre the plate under the support (overhang $1 cm): $2, OK.'],
  [/plaque ([\d,]+) × ([\d,]+) cm < ([\d,]+) × ([\d,]+) cm/g, 'Platte $1 × $2 cm < $3 × $4 cm', 'plate $1 × $2 cm < $3 × $4 cm'],
  [/épaisseur 1 × ([\d,]+) \/ 2 × ([\d,]+) \/ 3 × ([\d,]+) cm/g, 'Dicke 1 × $1 / 2 × $2 / 3 × $3 cm', 'thickness 1 × $1 / 2 × $2 / 3 × $3 cm'],
  [/Plaques du stock « ([^»]+) » selon le Prüfbuch/g, 'Lagerplatten „$1“ gemäß Prüfbuch', 'Stock plates “$1” as per the Prüfbuch'],
  [
    /Prüfbuch ([\w ]+), Auflage 4\.9 : la portance admissible doit être d’au moins 200 kN\/m² ; avec ([^,]+), l’installation sort du Prüfbuch \(étude spécifique du sol\)\./g,
    'Prüfbuch $1, Auflage 4.9: die zulässige Bodenpressung muss mindestens 200 kN/m² betragen; mit $2 liegt die Anlage außerhalb des Prüfbuchs (gesonderte Baugrundbetrachtung).',
    'Prüfbuch $1, condition 4.9: the allowable ground pressure must be at least 200 kN/m²; with $2 the installation is outside the Prüfbuch (specific ground study).',
  ],
  [/Calage inférieur au minimum du Prüfbuch ([\w ]+) \(plan ([\d-]+)\) pour /g, 'Unterpallung kleiner als das Minimum des Prüfbuchs $1 (Plan $2) für ', 'Packing smaller than the minimum of the Prüfbuch $1 (drawing $2) for '],
  [/ : non prévu par le plan ([\d-]+) \(Prüfbuch : /g, ': im Plan $1 nicht vorgesehen (Prüfbuch: ', ': not provided for in drawing $1 (Prüfbuch: '],
  // calage appui par appui (spreading.ts)
  [
    /trop mince pour répartir sur toute la plaque : emprise efficace (\d+) × (\d+) cm \(il faudrait (\d+) mm par plaque\)/g,
    'zu dünn, um über die ganze Platte zu verteilen: wirksame Fläche $1 × $2 cm (erforderlich $3 mm je Platte)',
    'too thin to spread over the whole plate: effective footprint $1 × $2 cm ($3 mm per plate needed)',
  ],
  [/bois écrasé sous l’appui \(σc,90,d = ([\d,]+) > ([\d,]+) N\/mm²\) — tôle acier sous le pied/g, 'Holz unter dem Auflager überdrückt (σc,90,d = $1 > $2 N/mm²) — Stahlblech unter den Fuß', 'timber crushed under the support (σc,90,d = $1 > $2 N/mm²) — steel plate under the foot'],
  [/appui (\d+) × (\d+) cm sur (\d+) × (\d+) cm : /g, 'Auflager $1 × $2 cm auf $3 × $4 cm: ', 'support $1 × $2 cm on $3 × $4 cm: '],
  [/Calage choisi : la plaque « ([^»]+) » n’est plus dans le stock, elle est ignorée\./g, 'Gewählte Unterpallung: Platte „$1“ nicht mehr im Lager, ignoriert.', 'Chosen packing: plate “$1” no longer in stock, ignored.'],
  // statico 18-0573 : éléments de façade, terrasses, lest (core/checks/facade.ts, core/terrace.ts, core/mods.ts)
  [/ : verre 44\.1 avec risque de chute \(étage\) — non admis, Stratobel 88\.2 obligatoire/g, ': VSG 44.1 mit Absturzgefahr (OG) — nicht zulässig, Stratobel 88.2 erforderlich', ': laminated glass 44.1 with fall risk (upper floor) — not permitted, Stratobel 88.2 required'],
  [/ : type de verre non indiqué — à l’étage, Stratobel 88\.2 obligatoire \(risque de chute\)/g, ': Glasart nicht angegeben — im OG ist Stratobel 88.2 erforderlich (Absturzgefahr)', ': glass type not given — on upper floors Stratobel 88.2 is required (fall risk)'],
  [/Vitrages 44\.1 du rez-de-chaussée : flèche ([\d,]+) mm > 25 mm sous le vent \(aptitude au service non satisfaite, résistance assurée\) — à évaluer par l’exploitant/g, 'VSG 44.1 im EG: Durchbiegung $1 mm > 25 mm unter Wind (Gebrauchstauglichkeit nicht eingehalten, Tragsicherheit erbracht) — vom Betreiber zu bewerten', 'Laminated glass 44.1 on the ground floor: deflection $1 mm > 25 mm under wind (serviceability not met, resistance ensured) — to be assessed by the operator'],
  [/ : verre 44\.1 seulement au rez-de-chaussée sans risque de chute/g, ': VSG 44.1 nur im EG ohne Absturzgefahr', ': laminated glass 44.1 only on the ground floor without fall risk'],
  [/ : panneau de mur autre que l’Isocab 60 mm du calcul 18-0573 § 3\.6\.4 — résistance au vent \(wk = ([\d,]+) kN\/m² sur 2,6 m\) à justifier par la fiche du fabricant/g, ': anderes Wandelement als Isocab 60 mm der Statik 18-0573 § 3.6.4 — Windwiderstand (wk = $1 kN/m² auf 2,6 m) durch Herstellerangaben nachzuweisen', ': wall panel other than the Isocab 60 mm of calculation 18-0573 § 3.6.4 — wind resistance (wk = $1 kN/m² over 2.6 m) to be justified by the manufacturer’s data sheet'],
  [/ : garde-corps sur une surface de plus de 350 kg\/m² — non couvert par statico 18-0573 § 3\.7 \(main courante 1,0 kN\/m à justifier\)/g, ': Geländer an einer Fläche über 350 kg/m² — nicht durch statico 18-0573 § 3.7 abgedeckt (Holmlast 1,0 kN/m nachzuweisen)', ': railing on an area above 350 kg/m² — not covered by statico 18-0573 § 3.7 (handrail load 1.0 kN/m to be justified)'],
  [/Lest de ([\d  ]+) kg sur ([\w-]+) \(étage\) : non admis, le lest ne se pose que dans les Viewbox du rez-de-chaussée \(statico 18-0573 § 5\.3\) — retirer ce lest/g, 'Ballast $1 kg auf $2 (OG): nicht zulässig, Ballast nur in den unteren Containern (EG) (statico 18-0573 § 5.3) — Ballast entfernen', 'Ballast of $1 kg on $2 (upper floor): not permitted, ballast only in the ground floor Viewbox (statico 18-0573 § 5.3) — remove this ballast'],
  [/ : emprise ([\d,]+) × ([\d,]+) m, élément terrasse 5,90 × 2,50 m attendu \(aligné sur les axes\) — terrasse non calculée\./g, ': Grundfläche $1 × $2 m, Terrassenelement 5,90 × 2,50 m erwartet (achsparallel) — Terrasse nicht berechnet.', ': footprint $1 × $2 m, terrace element 5.90 × 2.50 m expected (aligned with the axes) — terrace not calculated.'],
  [/ : posée sur ([\w-]+), qui porte déjà une Viewbox — terrasse non calculée\./g, ': auf $1, der bereits eine Viewbox trägt — Terrasse nicht berechnet.', ': resting on $1, which already carries a Viewbox — terrace not calculated.'],
  [/ : à ([\d,−-]+) m du sol sans Viewbox dessous — terrasse non calculée\./g, ': $1 m über Gelände ohne Viewbox darunter — Terrasse nicht berechnet.', ': $1 m above ground without a Viewbox below — terrace not calculated.'],
  [/\(entraxe ([\d,]+) cm, portée ([\d,]+) m\)/g, '(Raster $1 cm, Stützweite $2 m)', '(spacing $1 cm, span $2 m)'],
  [/, trois travées de ([\d,]+) cm/g, ', Dreifeldträger, Felder $1 cm', ', three spans of $1 cm'],
  [/Longueur de l’installation ([\d,]+) m > 30 m : au-delà des versions du calcul de type statico 18-0573 — calculée ici dans son ensemble, à faire valider par l’ingénieur\./g, 'Länge der Anlage $1 m > 30 m: über die Versionen der Typenstatik statico 18-0573 hinaus — hier insgesamt berechnet, vom Ingenieur zu bestätigen.', 'Length of the installation $1 m > 30 m: beyond the versions of the statico 18-0573 type calculation — calculated here as a whole, to be confirmed by the engineer.'],
  [/ · pied d’angle (\d)/g, ' · Eckfuß $1', ' · corner foot $1'],
  [/ · pied central (\d)/g, ' · Mittelfuß $1', ' · middle foot $1'],
];

/** Expressions (appliquées de la plus longue à la plus courte). */
const PHRASES: Rule[] = [
  [' — torsion (6.23)', ' — Torsion (6.23)', ' — torsion (6.23)'],
  [' — effort tranchant (6.17)', ' — Querkraft (6.17)', ' — shear (6.17)'],
  ['V,Ed / (k · Vpl,Rd) ≤ 1, k = réduction due à la torsion (1 si τt,Ed < 5 % τRd)', 'V,Ed / (k · Vpl,Rd) ≤ 1, k = Abminderung infolge Torsion (1 für τt,Ed < 5 % τRd)', 'V,Ed / (k · Vpl,Rd) ≤ 1, k = reduction due to torsion (1 if τt,Ed < 5 % τRd)'],
  // escaliers extérieurs
  ['Escalier — accroche des limons (crochets + 2 × M12)', 'Treppe — Einhängung der Wangen (Haken + 2 × M12)', 'Stair — stringer hooks (hooks + 2 × M12)'],
  ['Escalier — attache du palier à la Viewbox (M20)', 'Treppe — Podestanschluss an der Viewbox (M20)', 'Stair — landing connection to the Viewbox (M20)'],
  ['Escalier — accroche des limons', 'Treppe — Einhängung der Wangen', 'Stair — stringer hooks'],
  ['Escalier — attache du palier à la Viewbox', 'Treppe — Podestanschluss an der Viewbox', 'Stair — landing connection to the Viewbox'],
  ['Escalier — vérins Layher 60 des montants', 'Treppe — Layher Fußspindeln 60 der Stützen', 'Stair — Layher base jacks 60 of the posts'],
  ['Marches et paliers d’escalier', 'Treppenstufen und Podeste', 'Stair treads and landings'],
  ['Accroche du limon', 'Einhängung der Wange', 'Stringer hook'],
  ['accroche du limon côté Viewbox', 'Einhängung Wange viewboxseitig', 'stringer hook, Viewbox side'],
  ['accroche du limon extérieur', 'Einhängung Wange außen', 'outer stringer hook'],
  ['Attache du palier', 'Podestanschluss', 'Landing connection'],
  ['limon côté Viewbox, sous le palier', 'Wange viewboxseitig, unter dem Podest', 'stringer, Viewbox side, under the landing'],
  ['limon extérieur, sous le palier', 'Wange außen, unter dem Podest', 'outer stringer, under the landing'],
  ['limon côté Viewbox', 'Wange viewboxseitig', 'stringer, Viewbox side'],
  ['limon extérieur', 'Wange außen', 'outer stringer'],
  ['cadre de palier, côté Viewbox', 'Podestrahmen viewboxseitig', 'landing frame, Viewbox side'],
  ['cadre de palier, côté extérieur', 'Podestrahmen außen', 'landing frame, outer side'],
  ['cadre de palier, côté volée', 'Podestrahmen treppenseitig', 'landing frame, flight side'],
  ['cadre de palier, about', 'Podestrahmen, Stirnseite', 'landing frame, end'],
  ['Cadre de palier', 'Podestrahmen', 'Landing frame'],
  ['cadre de palier', 'Podestrahmen', 'landing frame'],
  ['Limon d’escalier', 'Treppenwange', 'Stair stringer'],
  ['limon d’escalier', 'Treppenwange', 'stair stringer'],
  ['Montant d’escalier', 'Treppenstütze', 'Stair post'],
  ['montant d’escalier', 'Treppenstütze', 'stair post'],
  ['Attache de montant de palier', 'Anschluss Podeststütze', 'Landing post connection'],
  ['attache de montant de palier', 'Anschluss Podeststütze', 'landing post connection'],
  ['attache du montant de palier', 'Anschluss Podeststütze', 'landing post connection'],
  ['pied de montant intermédiaire côté Viewbox', 'Fuß der Zwischenstütze viewboxseitig', 'foot of intermediate post, Viewbox side'],
  ['pied de montant intermédiaire extérieur', 'Fuß der Zwischenstütze außen', 'foot of outer intermediate post'],
  ['montant intermédiaire côté Viewbox', 'Zwischenstütze viewboxseitig', 'intermediate post, Viewbox side'],
  ['montant intermédiaire extérieur', 'Zwischenstütze außen', 'outer intermediate post'],
  ['pied de limon côté Viewbox', 'Wangenfuß viewboxseitig', 'stringer foot, Viewbox side'],
  ['pied de limon extérieur', 'Wangenfuß außen', 'outer stringer foot'],
  ['pied de Podeststütze', 'Fuß der Podeststütze', 'foot of landing post'],
  ['pied de poteau', 'Stützenfuß', 'post foot'],
  ['Pied de poteau', 'Stützenfuß', 'Post foot'],
  ['pied d’escalier', 'Treppenfuß', 'stair foot'],
  ['Pied d’escalier', 'Treppenfuß', 'Stair foot'],
  ['Vz crochets', 'Vz Haken', 'Vz hooks'],
  ['traction boulon', 'Schraube Zug', 'bolt tension'],
  ['effort le long du côté', 'Kraft entlang der Seite', 'force along the side'],
  ['statico 24-0569 § 3.2 (crochets 80 × 5 + 2 × M12-8.8)', 'statico 24-0569 § 3.2 (Haken 80 × 5 + 2 × M12-8.8)', 'statico 24-0569 § 3.2 (hooks 80 × 5 + 2 × M12-8.8)'],
  ['statico 24-0569 § 3.2 (2 × M20-8.8, capot 155 × 105 × 3 renforcé par un U 100 × 8)', 'statico 24-0569 § 3.2 (2 × M20-8.8, Spaltabdeckung 155 × 105 × 3 mit U 100 × 8 verstärkt)', 'statico 24-0569 § 3.2 (2 × M20-8.8, cover 155 × 105 × 3 reinforced by a U 100 × 8)'],
  ['statico 18-0573 § 3.8.3 ; EN 1993-1-1 6.3.3 (6.61) annexe B', 'statico 18-0573 § 3.8.3; EN 1993-1-1 6.3.3 (6.61) Anhang B', 'statico 18-0573 § 3.8.3; EN 1993-1-1 6.3.3 (6.61) Annex B'],
  ['Lcr = 2 · (h − h écrou) ; M = H · h', 'Lcr = 2 · (h − h Mutter); M = H · h', 'Lcr = 2 · (h − h nut); M = H · h'],
  ['statico 24-0569 § 2.1 – 2.2', 'statico 24-0569 § 2.1 – 2.2', 'statico 24-0569 § 2.1 – 2.2'],
  [
    'marches et platelage gk sur la volée et le palier (en plan) ; exploitation qk et H = V / 10 en service, escalier évacué hors service ; garde-corps sur les limons et le bord extérieur du palier',
    'Stufen und Belag gk auf Treppenlauf und Podest (Grundriss); Verkehrslast qk und H = V / 10 im Betrieb, Treppe außer Betrieb geräumt; Geländer auf den Wangen und dem äußeren Podestrand',
    'treads and decking gk on the flight and the landing (in plan); imposed load qk and H = V / 10 in service, stair evacuated out of service; railings on the stringers and the outer landing edge',
  ],
  ['Vérin Layher 60', 'Layher Fußspindel 60', 'Layher base jack 60'],
  [' (stock, quantité à vérifier au dépôt)', ' (Lager, Menge im Lager prüfen)', ' (stock, quantity to be checked at the depot)'],
  [' (stock)', ' (Lager)', ' (stock)'],
  [', à fleur de la Viewbox', ', bündig mit der Viewbox', ', flush with the Viewbox'],
  [', centré sous l’appui', ', mittig unter dem Auflager', ', centred under the support'],
  [' selon le Prüfbuch (plan ', ' gemäß Prüfbuch (Plan ', ' as per the Prüfbuch (drawing '],
  ['non conforme au Prüfbuch : ', 'nicht konform mit dem Prüfbuch: ', 'not compliant with the Prüfbuch: '],
  ['conforme au Prüfbuch', 'konform mit dem Prüfbuch', 'compliant with the Prüfbuch'],
  ['(minimum : ', '(Minimum: ', '(minimum: '],
  ['aucune plaque ; Prüfbuch : ', 'keine Platte; Prüfbuch: ', 'no plate; Prüfbuch: '],
  [' ; plaque excentrée : EN 1997-1 annexe D', '; ausmittige Platte: EN 1997-1 Anhang D', '; eccentric plate: EN 1997-1 Annex D'],
  ['plaque excentrée : emprise centrée sur la charge (B’ = B − 2 e)', 'ausmittige Platte: zur Last zentrische Fläche (B’ = B − 2 e)', 'eccentric plate: area centred on the load (B’ = B − 2 e)'],
  ['Platine de vérin', 'Spindelfußplatte', 'Jack base plate'],
  [' (plaque centrée sous l’appui : à fleur de la Viewbox, aucune plaque ne suffit, la charge est trop près du bord).', ' (Platte mittig unter dem Auflager: bündig mit der Viewbox reicht keine Platte, die Last liegt zu nah am Rand).', ' (plate centred under the support: flush with the Viewbox no plate is enough, the load is too close to the edge).'],
  [' (< Prüfbuch)', ' (< Prüfbuch)', ' (< Prüfbuch)'],
  // calage appui par appui (spreading.ts, calage.ts)
  ['Calage choisi, sur plaques de roulage', 'Gewählte Unterpallung, auf Fahrplatten', 'Chosen packing, on roadway plates'],
  ['Calage choisi', 'Gewählte Unterpallung', 'Chosen packing'],
  ['Plaques de roulage sur toute la surface', 'Fahrplatten auf der ganzen Fläche', 'Roadway plates over the whole area'],
  ['Plaques de roulage jointives', 'Fugenlose Fahrplatten', 'Jointed roadway plates'],
  [', sur plaques de roulage', ', auf Fahrplatten', ', on roadway plates'],
  ['pied posé sur les plaques de roulage', 'Fuß direkt auf den Fahrplatten', 'foot placed on the roadway plates'],
  ['pied posé directement au sol', 'Fuß direkt auf dem Boden', 'foot placed directly on the ground'],
  ['Sans plaque', 'Ohne Platte', 'No plate'],
  [' mm par vérin', ' mm je Spindelfuß', ' mm per jack'],
  [' cm par vérin', ' cm je Spindelfuß', ' cm per jack'],
  ['m² à couvrir (toute l’emprise au sol)', 'm² abzudecken (ganze Aufstandsfläche)', 'm² to cover (whole ground footprint)'],
  ['Multiplex bouleau', 'Birken-Multiplex', 'Birch multiplex'],
  ['Répartition par ', 'Lastverteilung durch ', 'Spreading by '],
  ['méthode statico (porte-à-faux diagonal) ; emprise efficace si la plaque est trop mince', 'Verfahren statico (diagonale Auskragung); wirksame Fläche, wenn die Platte zu dünn ist', 'statico method (diagonal cantilever); effective footprint if the plate is too thin'],
  ['capacité du fabricant, emprise = toute la plaque', 'Tragfähigkeit laut Hersteller, wirksame Fläche = ganze Platte', 'manufacturer capacity, footprint = whole plate'],
  ['sinon emprise réduite jusqu’à MEd = MRd', 'sonst verkleinerte Fläche bis MEd = MRd', 'otherwise reduced footprint until MEd = MRd'],
  ['toute la plaque répartit', 'die ganze Platte verteilt', 'the whole plate spreads'],
  ['emprise efficace', 'wirksame Fläche', 'effective footprint'],
  ['plaques de roulage jointives : charge verticale totale / surface couverte', 'fugenlose Fahrplatten: gesamte Vertikallast / bedeckte Fläche', 'jointed roadway plates: total vertical load / covered area'],
  ['pression uniforme sous l’emprise efficace de la dernière couche', 'gleichmäßige Pressung unter der wirksamen Fläche der untersten Lage', 'uniform pressure under the effective footprint of the bottom layer'],
  ['portance admissible', 'zulässige Bodenpressung', 'allowable bearing pressure'],
  [' > charge admissible du fabricant ', ' > zulässige Last laut Hersteller ', ' > manufacturer allowable load '],
  [' > charge ponctuelle admissible du support ', ' > zulässige Einzellast des Untergrunds ', ' > allowable point load of the support '],
  // neige
  ['s = μ1 · Ce · Ct · sk = 0,8 · sk sur les toitures du dernier niveau', 's = μ1 · Ce · Ct · sk = 0,8 · sk auf den Dächern des obersten Geschosses', 's = μ1 · Ce · Ct · sk = 0.8 · sk on the roofs of the top level'],
  ['Neige sur les toitures', 'Schnee auf den Dächern', 'Snow on the roofs'],
  [' S (neige)', ' S (Schnee)', ' S (snow)'],
  ['(hors service, neige, ', '(außer Betrieb, Schnee, ', '(out of service, snow, '],
  ['(en service, neige, ', '(in Betrieb, Schnee, ', '(in service, snow, '],
  ['ΣG + S (neige)', 'ΣG + S (Schnee)', 'ΣG + S (snow)'],
  ['Neige', 'Schnee', 'Snow'],
  // modifications de l'étude
  [', tête encastrée', ', Kopf eingespannt', ', fixed head'],
  [', tête articulée', ', Kopf gelenkig', ', pinned head'],
  [', avec croix de contreventement', ', mit Kreuzverband', ', with cross bracing'],
  [', sans croix de contreventement', ', ohne Verband', ', without bracing'],
  [' (toutes les Viewbox)', ' (alle Viewboxen)', ' (all units)'],
  ['Viewbox modifiées par l’étude : poids', 'In der Studie geänderte Viewboxen: Gewicht', 'Viewbox units modified by the study: weight'],
  ['pesée de la Viewbox standard + écart des barres acier (profils, hauteur des poteaux)', 'Wägung der Standard-Viewbox + Differenz der Stahlstäbe (Profile, Stützenhöhe)', 'weighing of the standard Viewbox + difference of the steel members (sections, column height)'],
  ['poids = pesée + Σ A · L · ρ · g (barres modifiées) − Σ A · L · ρ · g (barres du gabarit)', 'Gewicht = Wägung + Σ A · L · ρ · g (geänderte Stäbe) − Σ A · L · ρ · g (Stäbe der Vorlage)', 'weight = weighing + Σ A · L · ρ · g (modified members) − Σ A · L · ρ · g (template members)'],
  ['rives du plancher en ', 'Bodenrandträger als ', 'floor edge beams as '],
  ['rives de toiture en ', 'Dachrandträger als ', 'roof edge beams as '],
  ['traverses et lisses du plancher en ', 'Bodennebenträger als ', 'floor secondary beams as '],
  ['traverses et lisses de toiture en ', 'Dachnebenträger als ', 'roof secondary beams as '],
  ['poteaux en ', 'Stützen als ', 'columns as '],
  ['réceptions de pied d’angle en ', 'Fußaufnahmen an den Ecken als ', 'corner foot receptacles as '],
  ['réceptions de pied centrales en ', 'mittlere Fußaufnahmen als ', 'middle foot receptacles as '],
  ['Tube carré ', 'Quadratrohr ', 'Square tube '],
  ['Tube rectangulaire ', 'Rechteckrohr ', 'Rectangular tube '],
  ['Tube rond ', 'Rundrohr ', 'Round tube '],
  ['Rond plein Ø', 'Rundstahl Ø', 'Round bar Ø'],
  ['Bois ', 'Holz ', 'Timber '],
  [', formé à chaud', ', warmgefertigt', ', hot-finished'],
  [', formé à froid', ', kaltgefertigt', ', cold-formed'],
  // familles et éléments
  ['Angles poteau / cadre', 'Eckverbindungen Stütze / Rahmen', 'Column-to-frame corners'],
  ['Angle poteau / cadre', 'Eckverbindung Stütze / Rahmen', 'Column-to-frame corner'],
  ['Liaisons verticales entre Viewbox', 'Vertikale Verbindungen zwischen Viewboxen', 'Vertical connections between Viewbox units'],
  ['Liaison verticale', 'Vertikale Verbindung', 'Vertical connection'],
  ['Boulons horizontaux M20', 'Horizontale Verschraubungen M20', 'Horizontal M20 bolts'],
  ['Boulon horizontal', 'Horizontale Schraube', 'Horizontal bolt'],
  ['Traverse / lisse plancher', 'Bodennebenträger', 'Floor secondary beam'],
  ['Traverse / lisse toiture', 'Dachnebenträger', 'Roof secondary beam'],
  ['traverse / lisse plancher', 'Bodennebenträger', 'floor secondary beam'],
  ['traverse / lisse toiture', 'Dachnebenträger', 'roof secondary beam'],
  ['Rive plancher', 'Bodenrandträger', 'Floor edge beam'],
  ['Rive toiture', 'Dachrandträger', 'Roof edge beam'],
  ['rive plancher', 'Bodenrandträger', 'floor edge beam'],
  ['rive toiture', 'Dachrandträger', 'roof edge beam'],
  ['Réception de pied', 'Fußaufnahme', 'Foot receptacle'],
  ['réception de pied', 'Fußaufnahme', 'foot receptacle'],
  ['Plat de réception', 'Fußplatte', 'Foot plate'],
  ['plat de réception', 'Fußplatte', 'foot plate'],
  ['Réception centrale', 'Mittlere Fußaufnahme', 'Middle foot receptacle'],
  ['réception centrale', 'mittlere Fußaufnahme', 'middle foot receptacle'],
  ['liaison verticale d’angle', 'vertikale Eckverbindung', 'vertical corner link'],
  ['contact vertical', 'vertikaler Druckkontakt', 'vertical contact'],
  ['Contact vertical', 'Vertikaler Druckkontakt', 'Vertical contact'],
  ['boulon horizontal', 'horizontale Schraube', 'horizontal bolt'],
  ['contact d’angle', 'Druckkontakt Ecke', 'corner contact'],
  ['Contact d’angle', 'Druckkontakt Ecke', 'Corner contact'],
  ['Liaison verticale d’angle', 'Vertikale Eckverbindung', 'Vertical corner link'],
  ['Poteau', 'Stütze', 'Column'],
  ['poteau', 'Stütze', 'column'],
  ['boulon ', 'Schraube ', 'bolt '],
  // EC3
  [' — flambement et flexion (', ' — Biegeknicken und Biegung (', ' — flexural buckling and bending ('],
  [' — déversement', ' — Biegedrillknicken', ' — lateral-torsional buckling'],
  [' — résistance de la section (', ' — Querschnittstragfähigkeit (', ' — cross-section resistance ('],
  ['annexe B (méthode 2)', 'Anhang B (Verfahren 2)', 'Annex B (method 2)'],
  ['méthode statico', 'statico-Verfahren', 'statico method'],
  ['méthode classique', 'klassisches Verfahren', 'classic method'],
  ['idem (6.62) avec χz, kzy, kzz', 'ebenso (6.62) mit χz, kzy, kzz', 'likewise (6.62) with χz, kzy, kzz'],
  ['contraintes réduites EN 1993-1-5 § 10 : paroi', 'reduzierte Spannungen EN 1993-1-5 § 10: Querschnittsteil', 'reduced stresses EN 1993-1-5 § 10: plate'],
  ['fy,réd', 'fy,red', 'fy,red'],
  [' : section ou matériau inconnu', ': Querschnitt oder Material unbekannt', ': unknown section or material'],
  ['vérification EC3 non applicable (bois / autre matériau)', 'Nachweis nach EC3 nicht anwendbar (Holz / anderes Material)', 'EC3 check not applicable (timber / other material)'],
  ['hors des tranches de', 'außerhalb der Dickenbereiche von', 'outside the thickness ranges of'],
  ['section de classe 4, paroi', 'Querschnitt der Klasse 4, Querschnittsteil', 'class 4 section, plate'],
  ['trop élancée', 'zu schlank', 'too slender'],
  ['hors du domaine de l’outil', 'außerhalb des Anwendungsbereichs des Programms', 'outside the scope of the tool'],
  ['géométrie des parois inconnue, classe non déterminable', 'Geometrie der Querschnittsteile unbekannt, Klasse nicht bestimmbar', 'plate geometry unknown, class cannot be determined'],
  ['épaisseur', 'Dicke', 'thickness'],
  ['bloqué', 'blockiert', 'blocked'],
  // assemblages
  ['traction N / 70 kN, compression N / 176 kN (contact)', 'Zug N / 70 kN, Druck N / 176 kN (Kontakt)', 'tension N / 70 kN, compression N / 176 kN (contact)'],
  ['(un plat par sens)', '(eine Lasche je Richtung)', '(one plate per direction)'],
  ['H : (H − μ · Rz) / (n · HRd) par direction (n = plats de l’angle) ; soulèvement T / (n · TRd) ; Rz / NRd (contact)', 'H: (H − μ · Rz) / (n · HRd) je Richtung (n = Laschen der Ecke); Abheben T / (n · TRd); Rz / NRd (Kontakt)', 'H: (H − μ · Rz) / (n · HRd) per direction (n = plates of the corner); uplift T / (n · TRd); Rz / NRd (contact)'],
  ['compression Rz / NRd (contact) ; soulèvement T / (n · TRd), n = plats des demi-côtés extérieurs de l’angle', 'Druck Rz / NRd (Kontakt); Abheben T / (n · TRd), n = Laschen der äußeren Halbseiten der Ecke', 'compression Rz / NRd (contact); uplift T / (n · TRd), n = plates on the outer half-sides of the corner'],
  ['H = √(ΣHu² + ΣHv²) ; reste = max(0, H − μ · ΣRz) réparti selon u et v (direction sans plat : reprise par le frottement, cercle de Coulomb) ; Hu,reste / (nu · HRd), Hv,reste / (nv · HRd) ; n = moitié des plats des côtés extérieurs (un plat par sens)', 'H = √(ΣHu² + ΣHv²); Rest = max(0, H − μ · ΣRz) nach u und v aufgeteilt (Richtung ohne Lasche: von der Reibung aufgenommen, Coulomb-Reibkreis); Hu,Rest / (nu · HRd), Hv,Rest / (nv · HRd); n = Hälfte der Laschen der Außenseiten (eine Lasche je Richtung)', 'H = √(ΣHu² + ΣHv²); remainder = max(0, H − μ · ΣRz) split along u and v (direction without plate: taken by friction, Coulomb friction circle); Hu,rem / (nu · HRd), Hv,rem / (nv · HRd); n = half the plates of the outer sides (one plate per direction)'],
  ['angle sans plat d’empilement (ses deux côtés sont contre d’autres Viewbox) : le soulèvement n’est retenu par rien', 'Ecke ohne Stapellasche (beide Seiten an anderen Viewboxen): Abheben nicht gehalten', 'corner without stacking plate (both sides against other units): uplift not restrained'],
  ['Glissement entre Viewbox empilées', 'Gleiten zwischen gestapelten Viewboxen', 'Sliding between stacked units'],
  [' · plats d’empilement', ' · Stapellaschen', ' · stacking plates'],
  [' boulonnées entre elles', ' untereinander verschraubt', ' bolted together'],
  [' · groupe ', ' · Gruppe ', ' · group '],
  ['T soulèvement sans plat', 'T Abheben ohne Lasche', 'T uplift without plate'],
  ['H sans plat dans cette direction', 'H ohne Lasche in dieser Richtung', 'H without plate in this direction'],
  [' reste ', ' Rest ', ' remainder '],
  ['T soulèvement', 'T Abheben', 'T uplift'],
  ['H plats (petits côtés)', 'H Laschen (Stirnseiten)', 'H plates (short sides)'],
  ['H plats (grands côtés)', 'H Laschen (Längsseiten)', 'H plates (long sides)'],
  ['Contreventements ajoutés (plat + ridoir)', 'Zusätzliche Verbände (Flachstahl + Spannschloss)', 'Added bracing (flat + turnbuckle)'],
  ['Contreventements de surélévation (plat + ridoir)', 'Verbände der Aufständerung (Flachstahl + Spannschloss)', 'Raising bracing (flat + turnbuckle)'],
  ['Poteau de surélévation', 'Aufständerungsstütze', 'Raising post'],
  ['poteau de surélévation', 'Aufständerungsstütze', 'raising post'],
  ['croix de surélévation', 'Verband der Aufständerung', 'raising bracing'],
  ['contreventement ajouté', 'zusätzlicher Verband', 'added bracing'],
  ['appui rive sur rive', 'Auflager Randträger auf Randträger', 'rim-on-rim bearing'],
  ['cale ou plat d’appui à prévoir à chaque croisement', 'Futterblech oder Auflagerplatte an jeder Kreuzung vorsehen', 'packing or bearing plate required at each crossing'],
  ['poutre de reprise ajoutée', 'zusätzlicher Abfangträger', 'added transfer beam'],
  ['poteau d’appui ajouté', 'zusätzliche Stütze', 'added support post'],
  ['poteau d’appui', 'Stütze', 'support post'],
  ['attache de poutre du modèle', 'Anschluss eines Modellträgers', 'model beam attachment'],
  ['poutre du modèle', 'Träger aus dem Modell', 'model beam'],
  ['poteau du modèle', 'Stütze aus dem Modell', 'model post'],
  ['poutre de reprise', 'Abfangträger', 'transfer beam'],
  ['sur la poutre de reprise', 'auf dem Abfangträger', 'on the transfer beam'],
  ['sur la rive', 'auf dem Randträger', 'on the rim'],
  ['Contreventement', 'Verband', 'Bracing'],
  ['contreventement', 'Verband', 'bracing'],
  [', diagonale ', ', Diagonale ', ', diagonal '],
  ['Boulons horizontaux M16', 'Horizontale Verschraubungen M16', 'Horizontal M16 bolts'],
  [' — bois EN 1995-1-1', ' — Holz EN 1995-1-1', ' — timber EN 1995-1-1'],
  ['(contact)', '(Kontakt)', '(contact)'],
  ['M biaxial', 'M zweiachsig', 'M biaxial'],
  ['M uniaxial', 'M einachsig', 'M uniaxial'],
  ['N traction', 'N Zug', 'N tension'],
  ['N contact', 'N Kontakt', 'N contact'],
  ['H plats', 'H Laschen', 'H plates'],
  ['Pieds à vérin (tiges filetées)', 'Spindelfüße (Gewindestangen)', 'Jack feet (threaded rods)'],
  ['Pieds à vérin (VBX-JACK) : tige non renseignée dans la bibliothèque', 'Spindelfüße (VBX-JACK): Gewindestange in der Bibliothek nicht erfasst', 'Jack feet (VBX-JACK): rod not recorded in the library'],
  ['Pieds à vérin : platine 15 × 15 cm supposée (7-309-002, à confirmer).', 'Spindelfüße: Fußplatte 15 × 15 cm angenommen (7-309-002, zu bestätigen).', 'Jack feet: base plate 15 × 15 cm assumed (7-309-002, to be confirmed).'],
  ['N + M flambement', 'N + M Knicken', 'N + M buckling'],
  ['N + M section', 'N + M Querschnitt', 'N + M section'],
  ['noyau d3 : ', 'Kern d3: ', 'core d3: '],
  [', flambement ', ', Knicken ', ', buckling '],
  [' ; section ', '; Querschnitt ', '; section '],
  ['vérin d’angle', 'Spindelfuß Ecke', 'corner jack'],
  ['vérin central', 'Spindelfuß Mitte', 'middle jack'],
  [' mm par vérin', ' mm je Spindelfuß', ' mm per jack'],
  [' cm par vérin', ' cm je Spindelfuß', ' cm per jack'],
  ['Vérin ', 'Spindelfuß ', 'Jack '],
  ['tab. 3.4', 'Tab. 3.4', 'Table 3.4'],
  ['Angle Viewbox (VBX-CORNER) : capacités absentes de la bibliothèque', 'Viewbox-Ecke (VBX-CORNER): Tragfähigkeiten fehlen in der Bibliothek', 'Viewbox corner (VBX-CORNER): capacities missing from the library'],
  ['Contact poteau / couvercle (VBX-VERTICAL-CONTACT) : capacité absente de la bibliothèque', 'Kontakt Stütze / Deckel (VBX-VERTICAL-CONTACT): Tragfähigkeit fehlt in der Bibliothek', 'Column / cover contact (VBX-VERTICAL-CONTACT): capacity missing from the library'],
  ['Plats de liaison verticale (VBX-VERTICAL-PLATE) : capacités absentes de la bibliothèque', 'Vertikale Verbindungslaschen (VBX-VERTICAL-PLATE): Tragfähigkeiten fehlen in der Bibliothek', 'Vertical link plates (VBX-VERTICAL-PLATE): capacities missing from the library'],
  ['Contact vertical (VBX-VERTICAL-CONTACT) : capacité absente de la bibliothèque', 'Vertikaler Kontakt (VBX-VERTICAL-CONTACT): Tragfähigkeit fehlt in der Bibliothek', 'Vertical contact (VBX-VERTICAL-CONTACT): capacity missing from the library'],
  ['Boulons horizontaux (VBX-HORIZONTAL-BOLT) : capacités absentes de la bibliothèque', 'Horizontale Schrauben (VBX-HORIZONTAL-BOLT): Tragfähigkeiten fehlen in der Bibliothek', 'Horizontal bolts (VBX-HORIZONTAL-BOLT): capacities missing from the library'],
  [' tendue (', ' auf Zug beansprucht (', ' in tension ('],
  ['soulèvement de la Viewbox du dessus, capacité en traction non renseignée', 'Abheben der oberen Viewbox, Zugtragfähigkeit nicht erfasst', 'uplift of the upper Viewbox, tension capacity not recorded'],
  // plancher
  [' — contreplaqué ', ' — Sperrholz ', ' — plywood '],
  [' ; n couches croisées vissées, non collées : chacune porte qEd / n (valeurs de la direction faible pour chacune) ; η = max(vEd / (n · vRd) ; mEd / (n · mRd))', '; n kreuzweise verschraubte, nicht verklebte Lagen: jede trägt qEd / n (Werte der schwachen Richtung für jede); η = max(vEd / (n · vRd); mEd / (n · mRd))', '; n crossed layers, screwed, not glued: each carries qEd / n (weak-direction values for each); η = max(vEd / (n · vRd); mEd / (n · mRd))'],
  [/, (\d+) couches croisées/g, ', $1 kreuzweise Lagen', ', $1 crossed layers'],
  [', bande de 1 m', ', 1-m-Streifen', ', 1 m strip'],
  ['résistances du contreplaqué', 'Festigkeiten des Sperrholzes', 'strengths of the plywood'],
  ['Plancher', 'Boden', 'Floor'],
  // sol et calage
  ['Réaction caractéristique', 'Charakteristische Auflagerreaktion', 'Characteristic reaction'],
  ['combinaison caractéristique (ELS)', 'charakteristische Kombination (GZG)', 'characteristic combination (SLS)'],
  ['Pression au sol sous la longrine (sol élastique)', 'Bodenpressung unter dem Kantholz (elastische Bettung)', 'Ground pressure under the sleeper (elastic ground)'],
  ['Pression au sol', 'Nachweis der Bodenpressung', 'Ground pressure'],
  ['Flexion de la plaque (porte-à-faux diagonal)', 'Nachweis Biegung der Holzplatte (diagonaler Überstand)', 'Plate bending (diagonal overhang)'],
  ['Compression transversale sous l’appui', 'Nachweis Druck rechtwinklig zur Faser', 'Compression perpendicular to the grain under the support'],
  ['Compression transversale sous l’angle', 'Druck rechtwinklig zur Faser unter der Ecke', 'Compression perpendicular to the grain under the corner'],
  ['compression transversale dépassée sous l’appui', 'Druck rechtwinklig zur Faser unter dem Auflager überschritten', 'compression perpendicular to the grain exceeded under the support'],
  ['prévoir une tôle sous les angles (compression transversale du bois)', 'Stahlblech unter den Ecken vorsehen (Querdruck im Holz)', 'provide a steel plate under the corners (compression perpendicular to the grain)'],
  ['Flexion de la tôle acier', 'Biegung des Stahlblechs', 'Steel plate bending'],
  ['élastique, pression uniforme sous la tôle', 'elastisch, gleichmäßige Pressung unter dem Blech', 'elastic, uniform pressure under the plate'],
  ['hors des épaisseurs du commerce', 'außerhalb der handelsüblichen Dicken', 'beyond commercial thicknesses'],
  ['Répartition à 45° à travers des couches continues', 'Lastausbreitung unter 45° durch durchgehende Lagen', '45° spreading through continuous layers'],
  ['hypothèse de diffusion à 45° (couches continues, rigides et bien calées)', 'Annahme einer Lastausbreitung unter 45° (durchgehende, steife, satt aufliegende Lagen)', 'assumed 45° spreading (continuous, stiff, well-bedded layers)'],
  ['hypothèse de diffusion à 45° : à valider pour le matériau des couches', 'Lastausbreitung unter 45°: für das Material der Lagen zu bestätigen', '45° spreading: to be confirmed for the layer material'],
  ['Couches continues (diffusion à 45°)', 'Durchgehende Lagen (Lastausbreitung 45°)', 'Continuous layers (45° spreading)'],
  ['épaisseur totale', 'Gesamtdicke', 'total thickness'],
  ['poutre sur appuis élastiques (Winkler), charges caractéristiques', 'elastisch gebetteter Balken (Winkler), charakteristische Lasten', 'beam on elastic supports (Winkler), characteristic loads'],
  ['max. sol élastique / pression uniforme', 'max. elastische Bettung / gleichmäßige Pressung', 'max. elastic ground / uniform pressure'],
  ['appui continu', 'durchgehende Auflagerung', 'continuous support'],
  ['Flexion de la longrine', 'Biegung des Kantholzes', 'Sleeper bending'],
  ['Cisaillement de la longrine', 'Schub im Kantholz', 'Sleeper shear'],
  ['(moyenne ', '(Mittel ', '(mean '],
  ['Charge ponctuelle admissible du support', 'Zulässige Einzellast des Untergrunds', 'Allowable point load of the support'],
  ['donnée du bâtiment', 'Angabe des Gebäudes', 'building data'],
  ['capacité du fabricant', 'Tragfähigkeit laut Hersteller', 'manufacturer capacity'],
  ['Plaques de contreplaqué F40/30', 'Sperrholzplatten F40/30', 'Plywood plates F40/30'],
  ['Plaques du stock', 'Platten aus dem Lager', 'Plates from stock'],
  ['Plaque de répartition', 'Lastverteilungsplatte', 'Spreading plate'],
  ['Plaque « ', 'Platte « ', 'Plate « '],
  ['Longrines bois C24 sous les grands côtés', 'Kanthölzer C24 unter den Längsseiten', 'C24 timber sleepers under the long sides'],
  ['sous chaque grand côté', 'unter jeder Längsseite', 'under each long side'],
  ['Tôle acier S235', 'Stahlblech S235', 'Steel plate S235'],
  ['Contreplaqué F40/30', 'Sperrholz F40/30', 'Plywood F40/30'],
  ['Contreplaqué (stock)', 'Sperrholz (Lager)', 'Plywood (stock)'],
  ['Bois C24', 'Holz C24', 'Timber C24'],
  ['aucune épaisseur courante suffisante', 'keine handelsübliche Dicke ausreichend', 'no common thickness is sufficient'],
  ['épaisseur hors des tôles courantes', 'Dicke außerhalb der üblichen Bleche', 'thickness beyond common plates'],
  ['plus grande que', 'größer als', 'larger than'],
  ['de côté', 'Seitenlänge', 'side'],
  ['hors standard', 'außerhalb Standard', 'non-standard'],
  ['flambement (', 'Knicken (', 'buckling ('],
  ['déversement (', 'Biegedrillknicken (', 'LTB ('],
  ['section (', 'Querschnitt (', 'section ('],
  ['T soudé', 'T geschweißt', 'welded T'],
  ['Acier ', 'Stahl ', 'Steel '],
  ['U plié', 'U gekantet', 'cold-formed U'],
  ['C plié', 'C gekantet', 'cold-formed C'],
  ['formé à froid', 'kaltgefertigt', 'cold-formed'],
  ['Carré plein ', 'Vierkantstahl ', 'Square bar '],
  ['Plat ', 'Flachstahl ', 'Flat bar '],
  ['Contreplaqué F20/15', 'Sperrholz F20/15', 'Plywood F20/15'],
  ['Bois massif C24', 'Vollholz C24', 'Solid timber C24'],
  ['Lamellé-collé', 'Brettschichtholz', 'Glulam'],
  ['Solive bois', 'Holzbalken', 'Timber joist'],
  ['> portance', '> zul. Bodenpressung', '> bearing capacity'],
  ['pression ', 'Pressung ', 'pressure '],
  ['charge ', 'Last ', 'load '],
  [' mm par angle', ' mm je Ecke', ' mm per corner'],
  [' mm par groupe', ' mm je Gruppe', ' mm per group'],
  [' mm par pied central', ' mm je mittlerem Fuß', ' mm per middle foot'],
  [' cm par angle', ' cm je Ecke', ' cm per corner'],
  [' cm par groupe', ' cm je Gruppe', ' cm per group'],
  [' cm par pied central', ' cm je mittlerem Fuß', ' cm per middle foot'],
  ['sous chaque groupe', 'unter jeder Gruppe', 'under each group'],
  ['sous chaque pied', 'unter jedem Fuß', 'under each foot'],
  ['1 tôle ', '1 Blech ', '1 plate '],
  ['1 plaque ', '1 Platte ', '1 plate '],
  ['angle seul', 'einzelne Ecke', 'single corner'],
  ['pied central', 'mittlerer Fuß', 'middle foot'],
  ['Pieds centraux : surface de contact 15 × 15 cm supposée (à confirmer).', 'Mittlere Füße: Aufstandsfläche 15 × 15 cm angenommen (zu bestätigen).', 'Middle feet: contact area 15 × 15 cm assumed (to be confirmed).'],
  ['Longrines : aucune section de la liste ne suffit (6 pièces côte à côte au plus).', 'Kanthölzer: kein Querschnitt der Liste reicht aus (höchstens 6 nebeneinander).', 'Sleepers: no section of the list is sufficient (at most 6 side by side).'],
  ['Aucune solution standard pour tous les appuis : la moins mauvaise est chiffrée, une étude de répartition spécifique est nécessaire.', 'Keine Standardlösung für alle Auflager: die günstigste ist beziffert, eine gesonderte Lastverteilung ist erforderlich.', 'No standard solution for all supports: the least unfavourable one is quantified, a specific load spreading design is required.'],
  ['erf. W', 'erf. W', 'req. W'],
  ['erf. h', 'erf. h', 'req. h'],
  ['zul. σB', 'zul. σB', 'allow. σB'],
  // charges et vent
  ['poids pesé (plancher, sol, plafond et isolants compris) = G1 (barres, 78,5 kN/m³) + k · (G2 plafond + G4 sol)', 'gewogenes Gewicht (inkl. Boden, Bodenbelag, Decke und Dämmung) = G1 (Stäbe, 78,5 kN/m³) + k · (G2 Decke + G4 Boden)', 'weighed weight (floor, floor finish, ceiling and insulation included) = G1 (members, 78,5 kN/m³) + k · (G2 ceiling + G4 floor)'],
  [' (barres seules plus lourdes que la pesée : plafond et sol ignorés)', ' (Stäbe allein schwerer als die Wägung: Decke und Boden entfallen)', ' (members alone heavier than the weighed weight: ceiling and floor ignored)'],
  [' : modèle plus lourd, retenu (prudent)', ': Modell schwerer, angesetzt (auf der sicheren Seite)', ': model heavier, used (conservative)'],
  ['Garde-corps : au-delà de 357 kg/m² (3,5 kN/m²) sur une surface bordée de garde-corps, main courante à 1,0 kN/m à justifier (statico 18-0573 § 3.7).', 'Geländer: über 357 kg/m² (3,5 kN/m²) auf einer von Geländern umgebenen Fläche ist der Handlauf für 1,0 kN/m nachzuweisen (statico 18-0573 § 3.7).', 'Railings: above 357 kg/m² (3,5 kN/m²) on an area bordered by railings, the handrail must be justified for 1,0 kN/m (statico 18-0573 § 3.7).'],
  ['Charge maximale non cherchée : le calcul de l’étude a des vérifications bloquées ou en erreur.', 'Maximale Last nicht ermittelt: die Berechnung enthält blockierte oder fehlerhafte Nachweise.', 'Maximum load not searched: the analysis has blocked or failed checks.'],
  ['Charge maximale non calculée : ', 'Maximale Last nicht berechnet: ', 'Maximum load not calculated: '],
  ['Poids d’une Viewbox : modèle et pesée', 'Gewicht einer Viewbox: Modell und Wägung', 'Weight of one Viewbox: model and weighing'],
  ['G1 (barres, 78,5 kN/m³) + G2 (plafond) + G4 (sol) ≥ poids pesé, sinon complément Gc sur les rives du plancher', 'G1 (Stäbe, 78,5 kN/m³) + G2 (Decke) + G4 (Boden) ≥ gewogenes Gewicht, sonst Ergänzung Gc auf den Bodenrandträgern', 'G1 (members, 78,5 kN/m³) + G2 (ceiling) + G4 (floor) ≥ weighed weight, otherwise complement Gc on the floor edge beams'],
  [' : modèle plus lourd, pas de complément', ': Modell schwerer, keine Ergänzung', ': model heavier, no complement'],
  [' : complément Gc = ', ': Ergänzung Gc = ', ': complement Gc = '],
  ['pesée ', 'gewogen ', 'weighed '],
  ['vitesse d’arrêt d’exploitation', 'Abschaltgeschwindigkeit', 'operation stop speed'],
  ['Vent sur les côtés des Viewbox', 'Wind auf die Seiten der Viewboxen', 'Wind on the sides of the Viewbox units'],
  ['par rive (plancher et toiture)', 'je Randträger (Boden und Dach)', 'per edge beam (floor and roof)'],
  ['cp luv / lee / parallèle', 'cp Luv / Lee / parallel', 'cp windward / leeward / parallel'],
  ['Vent en service', 'Wind in Betrieb', 'Wind in service'],
  ['Vent hors service', 'Wind außer Betrieb', 'Wind out of service'],
  ['Exploitation en service', 'Verkehrslast in Betrieb', 'Imposed load in service'],
  ['Exploitation hors service', 'Verkehrslast außer Betrieb', 'Imposed load out of service'],
  ['Succion des toitures (hors service)', 'Dachsog (außer Betrieb)', 'Roof suction (out of service)'],
  ['Murs, vitrages, portes', 'Wände, Verglasungen, Türen', 'Walls, glazing, doors'],
  ['Complément de poids', 'Gewichtsergänzung', 'Weight complement'],
  ['Poids propre', 'Eigengewicht', 'Self-weight'],
  ['Plafonds', 'Decken', 'Ceilings'],
  ['Sols', 'Böden', 'Floors'],
  ['Garde-corps', 'Geländer', 'Railings'],
  ['q en service', 'q in Betrieb', 'q in service'],
  ['en service', 'in Betrieb', 'in service'],
  ['hors service', 'außer Betrieb', 'out of service'],
  ['pression saisie', 'eingegebener Druck', 'entered pressure'],
  ['qp saisi', 'qp eingegeben', 'qp entered'],
  ['zone ', 'Windzone ', 'zone '],
  ['Aucun côté exposé au vent.', 'Keine windbeanspruchte Seite.', 'No side exposed to wind.'],
  ['surface au vent seule, pas encore appliquée au calcul (vent calculé sur les côtés des Viewbox)', 'nur Windangriffsfläche, noch nicht in der Berechnung angesetzt (Wind auf den Seiten der Viewboxen)', 'wind area only, not yet applied in the analysis (wind computed on the sides of the Viewbox units)'],
  // stabilité et verdict
  ['μ requis = √(ΣRx² + ΣRy²) / ΣRz ≤ μ disponible', 'erf. μ = √(ΣRx² + ΣRy²) / ΣRz ≤ vorh. μ', 'required μ = √(ΣRx² + ΣRy²) / ΣRz ≤ available μ'],
  ['Système stable avec des appuis en compression seule (basculement vérifié dans le calcul non linéaire).', 'Das System ist mit nur druckaktiven Auflagern rechnerisch stabil (Kippsicherheit in der nichtlinearen Berechnung nachgewiesen).', 'The system is stable with compression-only supports (overturning verified in the nonlinear analysis).'],
  ['Combinaisons de stabilité non calculées.', 'Kombinationen der Lagesicherheit nicht berechnet.', 'Stability combinations not computed.'],
  ['Stabilité d’ensemble non assurée', 'Lagesicherheit nicht gegeben', 'Global stability not ensured'],
  ['et la structure devient instable (basculement)', 'und die Struktur wird instabil (Kippen)', 'and the structure becomes unstable (overturning)'],
  ['se soulève', 'hebt ab', 'lifts off'],
  ['s’ouvre', 'öffnet sich', 'opens'],
  ['l’appui ', 'das Auflager ', 'support '],
  ['le contact ', 'der Kontakt ', 'contact '],
  ['Système presque instable (mécanisme)', 'System nahezu instabil (Mechanismus)', 'System nearly unstable (mechanism)'],
  ['Système instable (mécanisme)', 'System instabil (Mechanismus)', 'Unstable system (mechanism)'],
  ['Système instable', 'System instabil', 'Unstable system'],
  ['Instabilité au 2ᵉ ordre (charge critique dépassée)', 'Instabilität nach Theorie II. Ordnung (Verzweigungslast überschritten)', 'Second-order instability (critical load exceeded)'],
  ['déplacement de', 'Verschiebung von', 'displacement of'],
  ['n’est pas tenu en', 'ist nicht gehalten in', 'is not restrained in'],
  ['n’est tenu par rien en', 'ist durch nichts gehalten in', 'is restrained by nothing in'],
  ['le nœud', 'der Knoten', 'node'],
  ['au nœud', 'am Knoten', 'at node'],
  ['nœud', 'Knoten', 'node'],
  ['Contacts indéterminés', 'Kontakte unbestimmt', 'Undetermined contacts'],
  ['Contact(s) à la limite', 'Kontakt(e) an der Grenze', 'Contact(s) at the limit'],
  ['effort résiduel', 'Restkraft', 'residual force'],
  ['négligé', 'vernachlässigt', 'neglected'],
  [' — lest ou ancrage nécessaire', ' — Ballast oder Verankerung erforderlich', ' — ballast or anchorage required'],
  [' — lest, ancrage ou frottement à justifier', ' — Ballast, Verankerung oder Reibbeiwert nachzuweisen', ' — ballast, anchorage or friction to be justified'],
  ['Glissement global', 'Globale Gleitsicherheit', 'Global sliding'],
  ['Basculement', 'Kippsicherheit', 'Overturning'],
  ['μ requis', 'erf. μ', 'required μ'],
  ['μ disponible', 'vorh. μ', 'available μ'],
  ['non calculé', 'nicht berechnet', 'not computed'],
  ['Pieds à vérins utilisés : capacité des vérins non renseignée (VBX-JACK)', 'Spindelfüße verwendet: Tragfähigkeit der Spindeln nicht erfasst (VBX-JACK)', 'Jack feet used: jack capacity not recorded (VBX-JACK)'],
  ['pas encore modélisées dans le calcul complet (escaliers, terrasses, poutres ajoutées) — verdict incomplet', 'noch nicht in der Gesamtberechnung modelliert (Treppen, Terrassen, zusätzliche Träger) — unvollständig', 'not yet modelled in the full analysis (stairs, terraces, added beams) — incomplete'],
  ['Aucune liaison horizontale entre', 'Keine horizontale Verschraubung zwischen', 'No horizontal connection between'],
  ['(perçages non alignés) : Viewbox reliées par contact seulement.', '(Bohrungen nicht fluchtend): Viewboxen nur über Kontakt verbunden.', '(drillings not aligned): units connected by contact only.'],
  ['dans le modèle (gabarit', 'im Modell (Vorlage', 'in the model (template'],
  ['replacée sur', 'aufgesetzt auf', 'placed on'],
  ['aucun angle de Viewbox sous son angle', 'keine Viewbox-Ecke unter ihrer Ecke', 'no Viewbox corner under its corner'],
  ['(empilement décalé ou appui non modélisé)', '(versetzt gestapelt oder Auflager nicht modelliert)', '(offset stack or support not modelled)'],
  ['Angles posés hors des angles de Viewbox :', 'Ecken außerhalb der Viewbox-Ecken aufgesetzt:', 'Corners placed away from Viewbox corners:'],
  ['rive ou poutre vérifiée en flexion, liaison vérifiée comme les plats d’empilement : perçages et attache à détailler.', 'Randträger bzw. Träger auf Biegung nachgewiesen, Verbindung wie die Stapellaschen nachgewiesen: Bohrungen und Anschluss im Detail festzulegen.', 'rim or beam checked in bending, connection checked like the stacking plates: drillings and attachment to be detailed.'],
  ['sur la rive de toiture de', 'auf dem Dachrandträger von', 'on the roof rim of'],
  ['à détailler', 'im Detail festzulegen', 'to be detailed'],
  ['jusqu’au sol', 'bis zum Boden', 'down to the ground'],
  ['posée de rive à rive sur la toiture de la Viewbox du dessous', 'von Rand zu Rand auf dem Dach der unteren Viewbox', 'spanning rim to rim on the roof of the unit below'],
  ['poutre(s) / poteau(x) du modèle calculé(s) : extrémités articulées sur la rive ou la barre la plus proche, poids propre compris, vent sur ces barres non compté — attaches à détailler.', 'Träger / Stützen aus dem Modell berechnet: Enden gelenkig am nächsten Randträger bzw. Stab, Eigengewicht berücksichtigt, Wind auf diese Stäbe nicht angesetzt — Anschlüsse im Detail festzulegen.', 'model beam(s) / post(s) computed: ends pinned to the nearest rim or member, self-weight included, wind on these members not counted — attachments to be detailed.'],
  ['Aucune Viewbox posée au sol : le modèle n’a pas d’appui.', 'Keine Viewbox auf dem Boden: das Modell hat kein Auflager.', 'No Viewbox on the ground: the model has no support.'],
  ['repère de la Viewbox introuvable', 'Achsensystem der Viewbox nicht gefunden', 'Viewbox frame not found'],
  // statico 18-0573 : éléments de façade et terrasses, calage, exploitation du rez-de-chaussée
  ['Rails des murs U 60 × 30 × 3 (S275)', 'Schienen der Wandelemente U 60 × 30 × 3 (S275)', 'Wall rails U 60 × 30 × 3 (S275)'],
  ['(deux travées, L = 1,3 m)', '(Zweifeldträger, L = 1,3 m)', '(two spans, L = 1,3 m)'],
  ['Fixation des rails : vis M8-8.8', 'Anbindung der Schienen: Schraube M8-8.8', 'Rail fixing: M8-8.8 screw'],
  ['Vitrage fixe : âme acier du profil 8 × 40 mm (S275)', 'Festverglasung: Stahlkern des Profils 8 × 40 mm (S275)', 'Fixed glazing: steel core of the profile 8 × 40 mm (S275)'],
  ['Verre feuilleté Stratobel 88.2 (risque de chute)', 'VSG Stratobel 88.2 (mit Absturzgefahr)', 'Laminated glass Stratobel 88.2 (fall risk)'],
  ['Verre feuilleté Stratobel 44.1 (rez-de-chaussée sans risque de chute)', 'VSG Stratobel 44.1 (EG ohne Absturzgefahr)', 'Laminated glass Stratobel 44.1 (ground floor without fall risk)'],
  ['σ(vent + main courante 1,0 kN/m à 1,1 m) / 2 vitres', 'σ(Wind + Holmlast 1,0 kN/m in 1,1 m Höhe) / 2 Scheiben', 'σ(wind + handrail 1,0 kN/m at 1,1 m) / 2 panes'],
  [' / 2 vitres', ' / 2 Scheiben', ' / 2 panes'],
  [' ; flèche ', '; Durchbiegung ', '; deflection '],
  ['DIN 18008-2 et -4', 'DIN 18008-2 und -4', 'DIN 18008-2 and -4'],
  ['Mur en panneau sandwich Kingspan Isocab 60 mm', 'Wandelement mit Sandwichelement Kingspan Isocab 60 mm', 'Sandwich panel wall Kingspan Isocab 60 mm'],
  ['(portée 2,6 m)', '(Stützweite 2,6 m)', '(span 2,6 m)'],
  ['Garde-corps des étages (montants 2 × 40 × 20 × 2 S275, platine 200 × 100 × 4, M20-8.8)', 'Geländer Obergeschoss (Stiele 2 × 40 × 20 × 2 S275, Grundplatte 200 × 100 × 4, M20-8.8)', 'Railings of the upper floors (posts 2 × 40 × 20 × 2 S275, base plate 200 × 100 × 4, M20-8.8)'],
  ['main courante pk = 0,5 kN/m (surfaces ≤ 350 kg/m²) : contraintes η = 1,01 ≈ 1,0 ; vis M20-8.8 : Ft,Ed = 23,63 kN ≤ 141 kN', 'Holmlast pk = 0,5 kN/m (Flächen ≤ 350 kg/m²): Spannungen η = 1,01 ≈ 1,0; Schrauben M20-8.8: Ft,Ed = 23,63 kN ≤ 141 kN', 'handrail load pk = 0,5 kN/m (areas ≤ 350 kg/m²): stresses η = 1,01 ≈ 1,0; M20-8.8 bolts: Ft,Ed = 23,63 kN ≤ 141 kN'],
  ['section : η = 1,00 (statico, arrondi) ; vis : η = 0,13', 'Querschnitt: η = 1,00 (statico, gerundet); Schrauben: η = 0,13', 'section: η = 1,00 (statico, rounded); bolts: η = 0,13'],
  ['Les fenêtres coulissantes vitrées existantes ne sont pas admises (statico 18-0573 § 1.2)', 'Die im Bestand vorhandenen Glas-Schiebefenster sind nicht zulässig (statico 18-0573 § 1.2)', 'The existing glazed sliding windows are not permitted (statico 18-0573 § 1.2)'],
  ['Terrasses au sol', 'Terrassen im EG', 'Terraces on the ground'],
  ['Terrasses sur toiture', 'Terrassen auf dem Dach', 'Terraces on a roof'],
  [' : rives ', ': Randträger ', ': edge beams '],
  ['U plié 200 × 80 × 4 (S275)', 'gekantetes U-Profil 200 × 80 × 4 (S275)', 'folded U 200 × 80 × 4 (S275)'],
  [', deux travées', ', Zweifeldträger', ', two spans'],
  [' avec la rive UNP 220 du dessous', ' mit dem UNP 220 darunter', ' with the UNP 220 edge beam below'],
  ['partagé selon les raideurs', 'nach Steifigkeit aufgeteilt', 'shared according to stiffness'],
  [' ; part ', '; Anteil ', '; share '],
  ['(la rive UNP 220 est vérifiée par le calcul complet)', '(UNP 220 in der Gesamtberechnung nachgewiesen)', '(the UNP 220 edge beam is checked by the full calculation)'],
  ['solive bois 150 × 50 C30', 'Holzbalken 150 × 50 C30', 'timber joist 150 × 50 C30'],
  ['platelage contreplaqué F20/15', 'Belag Sperrholz F20/15', 'plywood decking F20/15'],
  [' : réactions des pieds', ': Auflagerkräfte der Füße', ': foot reactions'],
  ['poutre à deux travées par rive : angles 0,375 · w · L/2, milieux 1,25 · w · L/2 (w = b / 2 · (g + q))', 'Zweifeldträger je Randträger: Ecken 0,375 · w · L/2, Mitte 1,25 · w · L/2 (w = b / 2 · (g + q))', 'two-span beam per edge: corners 0,375 · w · L/2, middle 1,25 · w · L/2 (w = b / 2 · (g + q))'],
  ['pied central : ', 'Mittelfuß: ', 'middle foot: '],
  [' ; plaque minimale du Prüfbuch 55 × 55 cm (statico : 56,2 kN pour toute la largeur)', '; Mindestunterpallung Prüfbuch 55 × 55 cm (statico: 56,2 kN für die ganze Breite)', '; minimum Prüfbuch plate 55 × 55 cm (statico: 56,2 kN for the full width)'],
  ['Terrasses au sol : poser les pieds aux 4 angles et au milieu des 2 grands côtés, chacun calé (statico 18-0573 § 3.5.1)', 'Terrassen im EG: Unterpallung am Anfang, Ende und mittig der Längsseiten (statico 18-0573 § 3.5.1)', 'Terraces on the ground: feet at the 4 corners and at mid-length of the 2 long sides, each one packed (statico 18-0573 § 3.5.1)'],
  ['Platelage Twinson P9555 30 mm (au lieu du contreplaqué) : 5,0 kN/m² selon Z-10.9-599 si portée ≤ 50 cm, appui ≥ 50 mm et qp ≤ 1,40 kN/m² — vérifier la validité de l’agrément', 'Belag TWINSON P9555 30 mm (statt Sperrholz): 5,0 kN/m² nach Z-10.9-599 bei Spannweite ≤ 50 cm, Auflagerbreite ≥ 50 mm und qp ≤ 1,40 kN/m² — Gültigkeit der Zulassung prüfen', 'Twinson P9555 30 mm decking (instead of plywood): 5,0 kN/m² according to Z-10.9-599 if span ≤ 50 cm, support width ≥ 50 mm and qp ≤ 1,40 kN/m² — check the validity of the approval'],
  ['Pieds des éléments terrasse : platine de vérin 15 × 15 cm supposée (à confirmer).', 'Füße der Terrassenelemente: Spindelplatte 15 × 15 cm angenommen (zu bestätigen).', 'Feet of the terrace elements: jack base plate 15 × 15 cm assumed (to be confirmed).'],
  ['pied d’angle de terrasse', 'Eckfuß Terrasse', 'terrace corner foot'],
  ['pied central de terrasse', 'Mittelfuß Terrasse', 'terrace middle foot'],
  ['Pied de terrasse', 'Terrassenfuß', 'Terrace foot'],
  ['pied de terrasse', 'Terrassenfuß', 'terrace foot'],
  ['Plancher du rez-de-chaussée', 'Boden Erdgeschoss', 'Ground floor deck'],
  [', trois travées', ', Dreifeldträger', ', three spans'],
  ['Plafonds et terrasses', 'Decken und Terrassen', 'Ceilings and terraces'],
  ['Éléments terrasse posés sur les toitures', 'Terrassenelemente auf den Dächern', 'Terrace elements on the roofs'],
  // assemblages hors gabarit (core/jointRevalidation.ts) et liaisons personnalisées (core/jointDesign.ts, stackJoint.ts)
  ['poteaux', 'Stützen', 'columns'],
  ['Poteaux', 'Stützen', 'Columns'],
  ['Liaison personnalisée', 'Sonderverbindung', 'Custom connection'],
  ['liaison personnalisée', 'Sonderverbindung', 'custom connection'],
  ['liaison entre Viewbox empilées : ', 'Verbindung gestapelter Viewboxen: ', 'connection between stacked units: '],
  [' à la place des plats d’empilement', ' anstelle der Stapellaschen', ' instead of the stacking plates'],
  [' en plus des plats d’empilement', ' zusätzlich zu den Stapellaschen', ' in addition to the stacking plates'],
  ['remplace les plats d’empilement', 'ersetzt die Stapellaschen', 'replaces the stacking plates'],
  ['en plus des plats d’empilement', 'zusätzlich zu den Stapellaschen', 'in addition to the stacking plates'],
  [' pièce(s) par angle', ' Teil(e) je Ecke', ' part(s) per corner'],
  ['prototype non qualifié — à faire valider par un ingénieur', 'nicht qualifizierter Prototyp — von einem Ingenieur zu prüfen', 'unqualified prototype — to be validated by an engineer'],
  ['capacité indicative — à faire valider par un ingénieur', 'Richtwert — von einem Ingenieur zu prüfen', 'indicative capacity — to be validated by an engineer'],
  ['prototype — non qualifié : calcul analytique, essai de qualification recommandé', 'Prototyp — nicht qualifiziert: nur analytisch berechnet, Qualifikationsversuch empfohlen', 'prototype — not qualified: analytical calculation only, qualification test recommended'],
  ['prototype — non qualifié', 'Prototyp — nicht qualifiziert', 'prototype — not qualified'],
  ['testé (essai de qualification)', 'geprüft (Qualifikationsversuch)', 'tested (qualification test)'],
  ['méthode des composants, EN 1993-1-8', 'Komponentenmethode, EN 1993-1-8', 'component method, EN 1993-1-8'],
  ['règle prudente de l’outil (capacités IDEA StatiCa du gabarit, statico 24-0571 § 3.7)', 'vorsichtige Regel des Programms (IDEA-StatiCa-Werte der Vorlage, statico 24-0571 § 3.7)', 'cautious rule of the tool (IDEA StatiCa capacities of the template, statico 24-0571 § 3.7)'],
  ['règle prudente hors gabarit', 'vorsichtige Regel außerhalb der Vorlage', 'cautious rule outside the template'],
  ['angle à platines non recalculable simplement', 'Stirnplattenecke nicht einfach nachrechenbar', 'end-plate corner not simply recalculable'],
  ['raideur en rotation du gabarit (3 500 kNcm/°) gardée, non recalculée', 'Drehfedersteifigkeit der Vorlage (3 500 kNcm/°) beibehalten, nicht neu berechnet', 'rotational stiffness of the template (3 500 kNcm/°) kept, not recalculated'],
  ['raideur non renseignée : raideur des liaisons d’angle d’origine gardée dans le calcul', 'Steifigkeit nicht angegeben: Steifigkeit der Originaleckverbindungen beibehalten', 'stiffness not given: stiffness of the original corner links kept'],
  ['bras de levier du plat 290 − h / 2', 'Hebelarm der Lasche 290 − h / 2', 'lever arm of the plate 290 − h / 2'],
  ['Angle poteau / cadre hors gabarit', 'Ecke Stütze / Rahmen außerhalb der Vorlage', 'Column / frame corner outside the template'],
  ['Boulons horizontaux — pression diamétrale', 'Horizontale Schrauben — Lochleibung', 'Horizontal bolts — bearing'],
  ['Boulons horizontaux — poinçonnement', 'Horizontale Schrauben — Durchstanzen', 'Horizontal bolts — punching shear'],
  ['Plats d’empilement — effort horizontal', 'Stapellaschen — Horizontalkraft', 'Stacking plates — horizontal force'],
  ['Contact vertical — paroi du poteau', 'Vertikaler Druckkontakt — Stützenwand', 'Vertical contact — column wall'],
  ['introduction dans la paroi du poteau', 'Lasteinleitung in die Stützenwand', 'load introduction into the column wall'],
  ['paroi du poteau', 'Stützenwand', 'column wall'],
  ['pression diamétrale dans l’âme de la rive', 'Lochleibung im Steg des Randträgers', 'bearing in the edge beam web'],
  ['pression diamétrale dans l’âme', 'Lochleibung im Steg', 'bearing in the web'],
  ['pression diamétrale dans la plaque', 'Lochleibung im Blech', 'bearing in the plate'],
  ['poinçonnement de l’âme', 'Durchstanzen des Stegs', 'punching shear of the web'],
  ['poinçonnement sous la tête ou l’écrou', 'Durchstanzen unter Kopf oder Mutter', 'punching under head or nut'],
  ['effort horizontal par plat', 'Horizontalkraft je Lasche', 'horizontal force per plate'],
  ['soulèvement par pièce', 'Abheben je Teil', 'uplift per part'],
  ['glissement le long du grand côté par pièce', 'Gleiten entlang der Längsseite je Teil', 'sliding along the long side per part'],
  ['glissement le long du petit côté par pièce', 'Gleiten entlang der Stirnseite je Teil', 'sliding along the short side per part'],
  ['glissement le long du grand côté', 'Gleiten entlang der Längsseite', 'sliding along the long side'],
  ['glissement le long du petit côté', 'Gleiten entlang der Stirnseite', 'sliding along the short side'],
  ['H le long du grand côté', 'H entlang der Längsseite', 'H along the long side'],
  ['H le long du petit côté', 'H entlang der Stirnseite', 'H along the short side'],
  ['T soulèvement : rien ne retient', 'T Abheben: nichts hält', 'T uplift: nothing holds'],
  ['H : rien ne retient dans cette direction', 'H: nichts hält in dieser Richtung', 'H: nothing holds in this direction'],
  ['ne retient rien en soulèvement', 'hält nichts gegen Abheben', 'holds nothing against uplift'],
  ['ne retient rien en glissement', 'hält nichts gegen Gleiten', 'holds nothing against sliding'],
  ['boulon en cisaillement', 'Schraube auf Abscheren', 'bolt in shear'],
  ['boulon en traction', 'Schraube auf Zug', 'bolt in tension'],
  ['filetage en prise (taraudage)', 'Gewindeeingriff (Innengewinde)', 'thread engagement (tapped hole)'],
  ['section nette de la plaque (traction)', 'Nettoquerschnitt des Blechs (Zug)', 'net section of the plate (tension)'],
  ['section brute de la plaque', 'Bruttoquerschnitt des Blechs', 'gross section of the plate'],
  ['plaque en flexion (console, une rotule)', 'Blech auf Biegung (Kragarm, ein Gelenk)', 'plate in bending (cantilever, one hinge)'],
  ['plaque en flexion (deux rotules, méthode statico)', 'Blech auf Biegung (zwei Fließgelenke, statico-Verfahren)', 'plate in bending (two hinges, statico method)'],
  ['soudure d’angle', 'Kehlnaht', 'fillet weld'],
  ['frottement sous serrage', 'Reibung unter Vorspannung', 'friction under preload'],
  ['appui en compression', 'Druckkontakt', 'bearing in compression'],
  ['plat 100 × 10', 'Flachstahl 100 × 10', 'flat 100 × 10'],
  ['âme de la rive UNP 220', 'Steg des Randträgers UNP 220', 'web of the edge beam UNP 220'],
  ['clamp (plaque pliée 15 mm)', 'Klemme (gekantetes Blech 15 mm)', 'clamp (bent plate 15 mm)'],
  ['gousset trapézoïdal (Viewbox du dessous)', 'Trapezknotenblech (untere Viewbox)', 'trapezoidal gusset (lower unit)'],
  ['soudure du gousset sur l’angle de toiture', 'Schweißnaht des Knotenblechs auf der Dachecke', 'weld of the gusset on the roof corner'],
  ['platine de pied (Viewbox du dessus)', 'Fußplatte (obere Viewbox)', 'foot plate (upper unit)'],
  ['M20 vissé dans le clamp', 'M20 in die Klemme geschraubt', 'M20 screwed into the clamp'],
  ['recalculé pour ', 'neu berechnet für ', 'recalculated for '],
  ['hors gabarit : capacités du gabarit × ', 'außerhalb der Vorlage: Werte der Vorlage × ', 'outside the template: template capacities × '],
  [', indicatives', ', Richtwerte', ', indicative'],
  ['moment biaxial My et Mz (chacun)', 'zweiachsiges Moment My und Mz (je)', 'biaxial moment My and Mz (each)'],
  ['moment dominant (uniaxial)', 'Hauptmoment (einachsig)', 'dominant moment (uniaxial)'],
  ['moment secondaire (uniaxial)', 'Nebenmoment (einachsig)', 'secondary moment (uniaxial)'],
  ['effort normal transmis par les boulons', 'von den Schrauben übertragene Normalkraft', 'axial force transferred by the bolts'],
  ['capacité saisie', 'eingegebene Tragfähigkeit', 'capacity entered'],
  ['non vérifiée', 'nicht geprüft', 'not verified'],
  ['posée sur des Viewbox de hauteurs différentes', 'auf Viewboxen unterschiedlicher Höhe gestellt', 'placed on units of different heights'],
  [' — mettre la même hauteur de poteaux sous une même Viewbox', ' — unter einer Viewbox gleiche Stützenhöhe vorsehen', ' — use the same column height under one unit'],
  ['Plats de liaison verticale (Viewbox empilées)', 'Stapellaschen (gestapelte Viewboxen)', 'Stacking plates (stacked units)'],
  ['Boulons horizontaux entre Viewbox juxtaposées', 'Horizontale Schrauben zwischen benachbarten Viewboxen', 'Horizontal bolts between adjacent units'],
  ['Angle poteau / cadre Viewbox', 'Ecke Stütze / Rahmen Viewbox', 'Viewbox column / frame corner'],
  ['Contact vertical entre Viewbox empilées', 'Vertikaler Druckkontakt gestapelter Viewboxen', 'Vertical contact between stacked units'],
  ['(gabarit ', '(Vorlage ', '(template '],
  [' (gabarit)', ' (Vorlage)', ' (template)'],
  ['rives ', 'Randträger ', 'edge beams '],
  ['rive', 'Randträger', 'edge beam'],
  ['Wel poteau', 'Wel Stütze', 'Wel column'],
  ['fy poteau', 'fy Stütze', 'fy column'],
  ['tw rive', 'tw Randträger', 'tw edge beam'],
  // mots de liaison (en dernier)
  [' et ', ' und ', ' and '],
  [' ou ', ' oder ', ' or '],
  [' avec ', ' mit ', ' with '],
  [' sans ', ' ohne ', ' without '],
  [' entre ', ' zwischen ', ' between '],
  [' sur ', ' auf ', ' on '],
  [' sous ', ' unter ', ' under '],
  [' par ', ' je ', ' per '],
  [' de ', ' von ', ' of '],
];

const COMPILED = new Map<Lang, Array<[string | RegExp, string]>>();

function rules(lang: 'de' | 'en'): Array<[string | RegExp, string]> {
  let r = COMPILED.get(lang);
  if (!r) {
    const k = lang === 'de' ? 1 : 2;
    const phrases = [...PHRASES].sort((a, b) => String(b[0]).length - String(a[0]).length);
    r = [...PATTERNS, ...phrases].map((x) => [x[0], x[k]] as [string | RegExp, string]);
    COMPILED.set(lang, r);
  }
  return r;
}

/** Typographie de la langue : pas d'espace avant « : » et « ; » en allemand et en anglais. */
export function typo(lang: Lang, text: string): string {
  return lang === 'fr' ? text : text.replace(/ ([:;])(?=\s|$)/g, '$1');
}

/** Texte du moteur (français) → langue du rapport ; en français : inchangé. */
export function translate(lang: Lang, text: string): string {
  if (lang === 'fr' || !text) return text;
  let s = text.replace(/'/g, '’');
  for (const [from, to] of rules(lang)) s = typeof from === 'string' ? s.split(from).join(to) : s.replace(from, to);
  s = s.replace(/« ?/g, lang === 'de' ? '„' : '“').replace(/ ?»/g, lang === 'de' ? '“' : '”');
  s = s.replace(/ ([:;])(?=\s|$)/g, '$1');
  if (lang === 'en') s = s.replace(/(\d),(\d)/g, '$1.$2');
  return s;
}

/** Mots français qui ne doivent plus apparaître dans un rapport allemand ou anglais (contrôle des tests). */
export const FRENCH_MARKERS = [
  'rive',
  'poteau',
  'tronçon',
  'angle',
  'plancher',
  'toiture',
  'côté',
  'liaison',
  'boulon',
  'flambement',
  'déversement',
  'résistance',
  'méthode',
  'combinaison',
  'classe',
  'contreplaqué',
  'plaque',
  'réaction',
  'pression',
  'glissement',
  'basculement',
  'requis',
  'disponible',
  'vent',
  'service',
  'charge',
  'sol',
  'avec',
  'sans',
  'et',
  'ou',
  'de',
  'du',
  'des',
  'le',
  'la',
  'les',
  'par',
  'pour',
  'sur',
  'sous',
];
