// Traduction des textes produits en français par le moteur de calcul (titres et formules des vérifications, libellés
// des éléments et des familles, solutions de calage, messages) pour le rapport en allemand ou en anglais. Table de
// correspondances : motifs d'abord (numéros d'angle, de tronçon…), puis expressions de la plus longue à la plus
// courte, enfin la typographie (guillemets, espace avant « : » et « ; ») et la virgule décimale en anglais.
// Les termes allemands suivent les notes statico. Fonction pure.
import type { Lang } from './i18n';

type Rule = readonly [string | RegExp, string, string];

/** Motifs (appliqués dans l'ordre). */
const PATTERNS: Rule[] = [
  [/grand côté (\d)/g, 'Längsseite $1', 'long side $1'],
  [/petit côté (\d)/g, 'Stirnseite $1', 'short side $1'],
  [/, tronçon (\d+)/g, ', Abschnitt $1', ', span $1'],
  [/angle (\d+), plancher/g, 'Ecke $1, Boden', 'corner $1, floor'],
  [/angle (\d+), toiture/g, 'Ecke $1, Dach', 'corner $1, roof'],
  [/liaison d’angle (\d+)/g, 'Eckverbindung $1', 'corner link $1'],
  [/\(([\d,]+) plat\)/g, '($1 Lasche)', '($1 plate)'],
  [/([\d,]+) plat\(s\)/g, '$1 Lasche(n)', '$1 plate(s)'],
  [/vérin d’angle (\d+)/g, 'Spindelfuß Ecke $1', 'corner jack $1'],
  [/vérin central (\d+)/g, 'Spindelfuß Mitte $1', 'middle jack $1'],
  [/Vérin Tr (\d+) × 5/g, 'Spindelfuß Tr $1 × 5', 'Jack Tr $1 × 5'],
  [/ : sortie ([\d,]+) cm > ([\d,]+) cm autorisés/g, ': Auszug $1 cm > $2 cm zulässig', ': extension $1 cm > $2 cm allowed'],
  [/(\d) angles sur une plaque/g, '$1 Ecken auf einer Unterpallung', '$1 corners on one plate'],
  [/groupe de (\d) angles/g, 'Gruppe mit $1 Ecken', 'group of $1 corners'],
  [/\bclasse (\d)/g, 'Klasse $1', 'class $1'],
  [/ · plancher, ([xy]) = /g, ' · Boden, $1 = ', ' · floor, $1 = '],
  [/ · toiture, ([xy]) = /g, ' · Dach, $1 = ', ' · roof, $1 = '],
  [/\((\d+) plaques?\)/g, '($1 Platte(n))', '($1 plate(s))'],
  [/(\d+) plaques empilées \(plus de (\d+)\)/g, '$1 gestapelte Platten (mehr als $2)', '$1 stacked plates (more than $2)'],
  [/(\d+) appui\(s\) soulevé\(s\) \(cas ([^)]+)\)/g, '$1 abhebende(s) Auflager (LK $2)', '$1 support(s) lifting off (comb. $2)'],
  [/\(cas ([^)]+)\)/g, '(LK $1)', '(comb. $1)'],
  [/ — cas ([A-Z0-9.]+)/g, ' — LK $1', ' — comb. $1'],
  [/\bcas ([A-Z0-9.]+)/g, 'LK $1', 'comb. $1'],
  [/(\d+) vérification\(s\) bloquée\(s\)/g, '$1 blockierte(r) Nachweis(e)', '$1 blocked check(s)'],
  [/(\d+) pièce\(s\) porteuse\(s\)/g, '$1 tragende(s) Bauteil(e)', '$1 load-bearing part(s)'],
  [/(\d+) ddl d’extrémité de barre sans rigidité, stabilisés/g, '$1 Stabendfreiheitsgrad(e) ohne Steifigkeit, stabilisiert', '$1 member end DOF(s) without stiffness, stabilised'],
  [/(\d+) nœud\(s\) dont une rotation n’est retenue par aucune barre \(articulations\) : rotation stabilisée/g, '$1 Knoten mit von keinem Stab gehaltener Verdrehung (Gelenke): Verdrehung stabilisiert', '$1 node(s) with a rotation restrained by no member (hinges): rotation stabilised'],
  [/stock insuffisant : (\d+) pièces nécessaires, (\d+) disponibles/g, 'Lagerbestand unzureichend: $1 Stück erforderlich, $2 vorhanden', 'insufficient stock: $1 pieces needed, $2 available'],
  [/posée (\d+) mm plus bas que le haut de/g, '$1 mm tiefer modelliert als die Oberkante von', 'modelled $1 mm lower than the top of'],
  [/posée (\d+) mm plus haut que le haut de/g, '$1 mm höher modelliert als die Oberkante von', 'modelled $1 mm higher than the top of'],
  [/(\d+) kg par tôle : manutention mécanique/g, '$1 kg je Blech: maschinelle Handhabung', '$1 kg per plate: mechanical handling'],
  // modifications de l'étude (core/mods.ts describeMods)
  [/lest de ([\d  ]+) kg sur le plancher de ([\w-]+)/g, 'Ballast $1 kg auf dem Boden von $2', 'ballast of $1 kg on the floor of $2'],
  [/contreventement en croix \(plat 60 × 6 \+ ridoir\) sur ([\w-]+), /g, 'Kreuzverband (Flachstahl 60 × 6 + Spannschloss) an $1, ', 'cross bracing (flat 60 × 6 + turnbuckle) on $1, '],
  [/Viewbox ([\w-]+) ajoutée contre ([\w-]+), /g, 'Viewbox $1 an $2 angebaut, ', 'Viewbox $1 added against $2, '],
  [/Viewbox ([\w-]+) ajoutée au-dessus de ([\w-]+)/g, 'Viewbox $1 auf $2 aufgesetzt', 'Viewbox $1 added on top of $2'],
  [/surélévation de (\d+) cm sur poteaux /g, 'Aufständerung um $1 cm auf Stützen ', 'raised by $1 cm on posts '],
  [/plats d’empilement : (\d+) par grand côté et (\d+) par petit côté/g, 'Stapellaschen: $1 je Längsseite und $2 je Stirnseite', 'stacking plates: $1 per long side and $2 per short side'],
  // calage appui par appui (spreading.ts)
  [
    /trop mince pour répartir sur toute la plaque : emprise efficace (\d+) × (\d+) cm \(il faudrait (\d+) mm par plaque\)/g,
    'zu dünn, um über die ganze Platte zu verteilen: wirksame Fläche $1 × $2 cm (erforderlich $3 mm je Platte)',
    'too thin to spread over the whole plate: effective footprint $1 × $2 cm ($3 mm per plate needed)',
  ],
  [/bois écrasé sous l’appui \(σc,90,d = ([\d,]+) > ([\d,]+) N\/mm²\) — tôle acier sous le pied/g, 'Holz unter dem Auflager überdrückt (σc,90,d = $1 > $2 N/mm²) — Stahlblech unter den Fuß', 'timber crushed under the support (σc,90,d = $1 > $2 N/mm²) — steel plate under the foot'],
  [/appui (\d+) × (\d+) cm sur (\d+) × (\d+) cm : /g, 'Auflager $1 × $2 cm auf $3 × $4 cm: ', 'support $1 × $2 cm on $3 × $4 cm: '],
  [/Calage choisi : la plaque « ([^»]+) » n’est plus dans le stock, elle est ignorée\./g, 'Gewählte Unterpallung: Platte „$1“ nicht mehr im Lager, ignoriert.', 'Chosen packing: plate “$1” no longer in stock, ignored.'],
];

/** Expressions (appliquées de la plus longue à la plus courte). */
const PHRASES: Rule[] = [
  // calage appui par appui (spreading.ts, calage.ts)
  ['Calage choisi, sur plaques de roulage', 'Gewählte Unterpallung, auf Fahrplatten', 'Chosen packing, on roadway plates'],
  ['Calage choisi', 'Gewählte Unterpallung', 'Chosen packing'],
  ['Plaques de roulage sur toute la surface', 'Fahrplatten auf der ganzen Fläche', 'Roadway plates over the whole area'],
  ['Plaques de roulage jointives', 'Fugenlose Fahrplatten', 'Jointed roadway plates'],
  [', sur plaques de roulage', ', auf Fahrplatten', ', on roadway plates'],
  ['pied posé sur les plaques de roulage', 'Fuß direkt auf den Fahrplatten', 'foot placed on the roadway plates'],
  ['pied posé directement au sol', 'Fuß direkt auf dem Boden', 'foot placed directly on the ground'],
  ['Sans plaque', 'Ohne Platte', 'No plate'],
  [' mm par vérin', ' mm je Spindelfuß', ' mm per jack'],
  [' cm par vérin', ' cm je Spindelfuß', ' cm per jack'],
  ['m² à couvrir (toute l’emprise au sol)', 'm² abzudecken (ganze Aufstandsfläche)', 'm² to cover (whole ground footprint)'],
  ['Multiplex bouleau', 'Birken-Multiplex', 'Birch multiplex'],
  ['Répartition par ', 'Lastverteilung durch ', 'Spreading by '],
  ['méthode statico (porte-à-faux diagonal) ; emprise efficace si la plaque est trop mince', 'Verfahren statico (diagonale Auskragung); wirksame Fläche, wenn die Platte zu dünn ist', 'statico method (diagonal cantilever); effective footprint if the plate is too thin'],
  ['capacité du fabricant, emprise = toute la plaque', 'Tragfähigkeit laut Hersteller, wirksame Fläche = ganze Platte', 'manufacturer capacity, footprint = whole plate'],
  ['sinon emprise réduite jusqu’à MEd = MRd', 'sonst verkleinerte Fläche bis MEd = MRd', 'otherwise reduced footprint until MEd = MRd'],
  ['toute la plaque répartit', 'die ganze Platte verteilt', 'the whole plate spreads'],
  ['emprise efficace', 'wirksame Fläche', 'effective footprint'],
  ['plaques de roulage jointives : charge verticale totale / surface couverte', 'fugenlose Fahrplatten: gesamte Vertikallast / bedeckte Fläche', 'jointed roadway plates: total vertical load / covered area'],
  ['pression uniforme sous l’emprise efficace de la dernière couche', 'gleichmäßige Pressung unter der wirksamen Fläche der untersten Lage', 'uniform pressure under the effective footprint of the bottom layer'],
  ['portance admissible', 'zulässige Bodenpressung', 'allowable bearing pressure'],
  [' > charge admissible du fabricant ', ' > zulässige Last laut Hersteller ', ' > manufacturer allowable load '],
  [' > charge ponctuelle admissible du support ', ' > zulässige Einzellast des Untergrunds ', ' > allowable point load of the support '],
  // neige
  ['s = μ1 · Ce · Ct · sk = 0,8 · sk sur les toitures du dernier niveau', 's = μ1 · Ce · Ct · sk = 0,8 · sk auf den Dächern des obersten Geschosses', 's = μ1 · Ce · Ct · sk = 0.8 · sk on the roofs of the top level'],
  ['Neige sur les toitures', 'Schnee auf den Dächern', 'Snow on the roofs'],
  [' S (neige)', ' S (Schnee)', ' S (snow)'],
  ['(hors service, neige, ', '(außer Betrieb, Schnee, ', '(out of service, snow, '],
  ['(en service, neige, ', '(in Betrieb, Schnee, ', '(in service, snow, '],
  ['ΣG + S (neige)', 'ΣG + S (Schnee)', 'ΣG + S (snow)'],
  ['Neige', 'Schnee', 'Snow'],
  // modifications de l'étude
  [', tête encastrée', ', Kopf eingespannt', ', fixed head'],
  [', tête articulée', ', Kopf gelenkig', ', pinned head'],
  [', avec croix de contreventement', ', mit Kreuzverband', ', with cross bracing'],
  [', sans croix de contreventement', ', ohne Verband', ', without bracing'],
  [' (toutes les Viewbox)', ' (alle Viewboxen)', ' (all units)'],
  ['rives du plancher en ', 'Bodenrandträger als ', 'floor edge beams as '],
  ['rives de toiture en ', 'Dachrandträger als ', 'roof edge beams as '],
  ['traverses et lisses du plancher en ', 'Bodennebenträger als ', 'floor secondary beams as '],
  ['traverses et lisses de toiture en ', 'Dachnebenträger als ', 'roof secondary beams as '],
  ['poteaux en ', 'Stützen als ', 'columns as '],
  ['réceptions de pied d’angle en ', 'Fußaufnahmen an den Ecken als ', 'corner foot receptacles as '],
  ['réceptions de pied centrales en ', 'mittlere Fußaufnahmen als ', 'middle foot receptacles as '],
  ['Tube carré ', 'Quadratrohr ', 'Square tube '],
  ['Tube rectangulaire ', 'Rechteckrohr ', 'Rectangular tube '],
  ['Tube rond ', 'Rundrohr ', 'Round tube '],
  ['Rond plein Ø', 'Rundstahl Ø', 'Round bar Ø'],
  ['Bois ', 'Holz ', 'Timber '],
  [', formé à chaud', ', warmgefertigt', ', hot-finished'],
  [', formé à froid', ', kaltgefertigt', ', cold-formed'],
  // familles et éléments
  ['Angles poteau / cadre', 'Eckverbindungen Stütze / Rahmen', 'Column-to-frame corners'],
  ['Angle poteau / cadre', 'Eckverbindung Stütze / Rahmen', 'Column-to-frame corner'],
  ['Liaisons verticales entre Viewbox', 'Vertikale Verbindungen zwischen Viewboxen', 'Vertical connections between Viewbox units'],
  ['Liaison verticale', 'Vertikale Verbindung', 'Vertical connection'],
  ['Boulons horizontaux M20', 'Horizontale Verschraubungen M20', 'Horizontal M20 bolts'],
  ['Boulon horizontal', 'Horizontale Schraube', 'Horizontal bolt'],
  ['Traverse / lisse plancher', 'Bodennebenträger', 'Floor secondary beam'],
  ['Traverse / lisse toiture', 'Dachnebenträger', 'Roof secondary beam'],
  ['traverse / lisse plancher', 'Bodennebenträger', 'floor secondary beam'],
  ['traverse / lisse toiture', 'Dachnebenträger', 'roof secondary beam'],
  ['Rive plancher', 'Bodenrandträger', 'Floor edge beam'],
  ['Rive toiture', 'Dachrandträger', 'Roof edge beam'],
  ['rive plancher', 'Bodenrandträger', 'floor edge beam'],
  ['rive toiture', 'Dachrandträger', 'roof edge beam'],
  ['Réception de pied', 'Fußaufnahme', 'Foot receptacle'],
  ['réception de pied', 'Fußaufnahme', 'foot receptacle'],
  ['Plat de réception', 'Fußplatte', 'Foot plate'],
  ['plat de réception', 'Fußplatte', 'foot plate'],
  ['Réception centrale', 'Mittlere Fußaufnahme', 'Middle foot receptacle'],
  ['réception centrale', 'mittlere Fußaufnahme', 'middle foot receptacle'],
  ['liaison verticale d’angle', 'vertikale Eckverbindung', 'vertical corner link'],
  ['contact vertical', 'vertikaler Druckkontakt', 'vertical contact'],
  ['Contact vertical', 'Vertikaler Druckkontakt', 'Vertical contact'],
  ['boulon horizontal', 'horizontale Schraube', 'horizontal bolt'],
  ['contact d’angle', 'Druckkontakt Ecke', 'corner contact'],
  ['Contact d’angle', 'Druckkontakt Ecke', 'Corner contact'],
  ['Liaison verticale d’angle', 'Vertikale Eckverbindung', 'Vertical corner link'],
  ['Poteau', 'Stütze', 'Column'],
  ['poteau', 'Stütze', 'column'],
  ['boulon ', 'Schraube ', 'bolt '],
  // EC3
  [' — flambement et flexion (', ' — Biegeknicken und Biegung (', ' — flexural buckling and bending ('],
  [' — déversement', ' — Biegedrillknicken', ' — lateral-torsional buckling'],
  [' — résistance de la section (', ' — Querschnittstragfähigkeit (', ' — cross-section resistance ('],
  ['annexe B (méthode 2)', 'Anhang B (Verfahren 2)', 'Annex B (method 2)'],
  ['méthode statico', 'statico-Verfahren', 'statico method'],
  ['méthode classique', 'klassisches Verfahren', 'classic method'],
  ['idem (6.62) avec χz, kzy, kzz', 'ebenso (6.62) mit χz, kzy, kzz', 'likewise (6.62) with χz, kzy, kzz'],
  ['contraintes réduites EN 1993-1-5 § 10 : paroi', 'reduzierte Spannungen EN 1993-1-5 § 10: Querschnittsteil', 'reduced stresses EN 1993-1-5 § 10: plate'],
  ['fy,réd', 'fy,red', 'fy,red'],
  [' : section ou matériau inconnu', ': Querschnitt oder Material unbekannt', ': unknown section or material'],
  ['vérification EC3 non applicable (bois / autre matériau)', 'Nachweis nach EC3 nicht anwendbar (Holz / anderes Material)', 'EC3 check not applicable (timber / other material)'],
  ['hors des tranches de', 'außerhalb der Dickenbereiche von', 'outside the thickness ranges of'],
  ['section de classe 4, paroi', 'Querschnitt der Klasse 4, Querschnittsteil', 'class 4 section, plate'],
  ['trop élancée', 'zu schlank', 'too slender'],
  ['hors du domaine de l’outil', 'außerhalb des Anwendungsbereichs des Programms', 'outside the scope of the tool'],
  ['géométrie des parois inconnue, classe non déterminable', 'Geometrie der Querschnittsteile unbekannt, Klasse nicht bestimmbar', 'plate geometry unknown, class cannot be determined'],
  ['épaisseur', 'Dicke', 'thickness'],
  ['bloqué', 'blockiert', 'blocked'],
  // assemblages
  ['traction N / 70 kN, compression N / 176 kN (contact)', 'Zug N / 70 kN, Druck N / 176 kN (Kontakt)', 'tension N / 70 kN, compression N / 176 kN (contact)'],
  ['(un plat par sens)', '(eine Lasche je Richtung)', '(one plate per direction)'],
  ['H : (H − μ · Rz) / (n · HRd) par direction (n = plats de l’angle) ; soulèvement T / (n · TRd) ; Rz / NRd (contact)', 'H: (H − μ · Rz) / (n · HRd) je Richtung (n = Laschen der Ecke); Abheben T / (n · TRd); Rz / NRd (Kontakt)', 'H: (H − μ · Rz) / (n · HRd) per direction (n = plates of the corner); uplift T / (n · TRd); Rz / NRd (contact)'],
  ['compression Rz / NRd (contact) ; soulèvement T / (n · TRd), n = plats des demi-côtés extérieurs de l’angle', 'Druck Rz / NRd (Kontakt); Abheben T / (n · TRd), n = Laschen der äußeren Halbseiten der Ecke', 'compression Rz / NRd (contact); uplift T / (n · TRd), n = plates on the outer half-sides of the corner'],
  ['H = √(ΣHu² + ΣHv²) ; reste = max(0, H − μ · ΣRz) réparti selon u et v ; Hu,reste / (nu · HRd), Hv,reste / (nv · HRd) ; n = moitié des plats des côtés extérieurs (un plat par sens)', 'H = √(ΣHu² + ΣHv²); Rest = max(0, H − μ · ΣRz) nach u und v aufgeteilt; Hu,Rest / (nu · HRd), Hv,Rest / (nv · HRd); n = Hälfte der Laschen der Außenseiten (eine Lasche je Richtung)', 'H = √(ΣHu² + ΣHv²); remainder = max(0, H − μ · ΣRz) split along u and v; Hu,rem / (nu · HRd), Hv,rem / (nv · HRd); n = half the plates of the outer sides (one plate per direction)'],
  ['angle sans plat d’empilement (ses deux côtés sont contre d’autres Viewbox) : le soulèvement n’est retenu par rien', 'Ecke ohne Stapellasche (beide Seiten an anderen Viewboxen): Abheben nicht gehalten', 'corner without stacking plate (both sides against other units): uplift not restrained'],
  ['Glissement entre Viewbox empilées', 'Gleiten zwischen gestapelten Viewboxen', 'Sliding between stacked units'],
  [' · plats d’empilement', ' · Stapellaschen', ' · stacking plates'],
  ['T soulèvement sans plat', 'T Abheben ohne Lasche', 'T uplift without plate'],
  ['H sans plat dans cette direction', 'H ohne Lasche in dieser Richtung', 'H without plate in this direction'],
  [' reste ', ' Rest ', ' remainder '],
  ['T soulèvement', 'T Abheben', 'T uplift'],
  ['H plats (petits côtés)', 'H Laschen (Stirnseiten)', 'H plates (short sides)'],
  ['H plats (grands côtés)', 'H Laschen (Längsseiten)', 'H plates (long sides)'],
  ['Contreventements ajoutés (plat + ridoir)', 'Zusätzliche Verbände (Flachstahl + Spannschloss)', 'Added bracing (flat + turnbuckle)'],
  ['Contreventements de surélévation (plat + ridoir)', 'Verbände der Aufständerung (Flachstahl + Spannschloss)', 'Raising bracing (flat + turnbuckle)'],
  ['Poteau de surélévation', 'Aufständerungsstütze', 'Raising post'],
  ['poteau de surélévation', 'Aufständerungsstütze', 'raising post'],
  ['croix de surélévation', 'Verband der Aufständerung', 'raising bracing'],
  ['contreventement ajouté', 'zusätzlicher Verband', 'added bracing'],
  ['Contreventement', 'Verband', 'Bracing'],
  ['contreventement', 'Verband', 'bracing'],
  [', diagonale ', ', Diagonale ', ', diagonal '],
  ['Boulons horizontaux M16', 'Horizontale Verschraubungen M16', 'Horizontal M16 bolts'],
  [' — bois EN 1995-1-1', ' — Holz EN 1995-1-1', ' — timber EN 1995-1-1'],
  ['(contact)', '(Kontakt)', '(contact)'],
  ['M biaxial', 'M zweiachsig', 'M biaxial'],
  ['M uniaxial', 'M einachsig', 'M uniaxial'],
  ['N traction', 'N Zug', 'N tension'],
  ['N contact', 'N Kontakt', 'N contact'],
  ['H plats', 'H Laschen', 'H plates'],
  ['Pieds à vérin (tiges filetées)', 'Spindelfüße (Gewindestangen)', 'Jack feet (threaded rods)'],
  ['Pieds à vérin (VBX-JACK) : tige non renseignée dans la bibliothèque', 'Spindelfüße (VBX-JACK): Gewindestange in der Bibliothek nicht erfasst', 'Jack feet (VBX-JACK): rod not recorded in the library'],
  ['Pieds à vérin : platine 15 × 15 cm supposée (7-309-002, à confirmer).', 'Spindelfüße: Fußplatte 15 × 15 cm angenommen (7-309-002, zu bestätigen).', 'Jack feet: base plate 15 × 15 cm assumed (7-309-002, to be confirmed).'],
  ['N + M flambement', 'N + M Knicken', 'N + M buckling'],
  ['N + M section', 'N + M Querschnitt', 'N + M section'],
  ['noyau d3 : ', 'Kern d3: ', 'core d3: '],
  [', flambement ', ', Knicken ', ', buckling '],
  [' ; section ', '; Querschnitt ', '; section '],
  ['vérin d’angle', 'Spindelfuß Ecke', 'corner jack'],
  ['vérin central', 'Spindelfuß Mitte', 'middle jack'],
  [' mm par vérin', ' mm je Spindelfuß', ' mm per jack'],
  [' cm par vérin', ' cm je Spindelfuß', ' cm per jack'],
  ['Vérin ', 'Spindelfuß ', 'Jack '],
  ['tab. 3.4', 'Tab. 3.4', 'Table 3.4'],
  ['Angle Viewbox (VBX-CORNER) : capacités absentes de la bibliothèque', 'Viewbox-Ecke (VBX-CORNER): Tragfähigkeiten fehlen in der Bibliothek', 'Viewbox corner (VBX-CORNER): capacities missing from the library'],
  ['Contact poteau / couvercle (VBX-VERTICAL-CONTACT) : capacité absente de la bibliothèque', 'Kontakt Stütze / Deckel (VBX-VERTICAL-CONTACT): Tragfähigkeit fehlt in der Bibliothek', 'Column / cover contact (VBX-VERTICAL-CONTACT): capacity missing from the library'],
  ['Plats de liaison verticale (VBX-VERTICAL-PLATE) : capacités absentes de la bibliothèque', 'Vertikale Verbindungslaschen (VBX-VERTICAL-PLATE): Tragfähigkeiten fehlen in der Bibliothek', 'Vertical link plates (VBX-VERTICAL-PLATE): capacities missing from the library'],
  ['Contact vertical (VBX-VERTICAL-CONTACT) : capacité absente de la bibliothèque', 'Vertikaler Kontakt (VBX-VERTICAL-CONTACT): Tragfähigkeit fehlt in der Bibliothek', 'Vertical contact (VBX-VERTICAL-CONTACT): capacity missing from the library'],
  ['Boulons horizontaux (VBX-HORIZONTAL-BOLT) : capacités absentes de la bibliothèque', 'Horizontale Schrauben (VBX-HORIZONTAL-BOLT): Tragfähigkeiten fehlen in der Bibliothek', 'Horizontal bolts (VBX-HORIZONTAL-BOLT): capacities missing from the library'],
  [' tendue (', ' auf Zug beansprucht (', ' in tension ('],
  ['soulèvement de la Viewbox du dessus, capacité en traction non renseignée', 'Abheben der oberen Viewbox, Zugtragfähigkeit nicht erfasst', 'uplift of the upper Viewbox, tension capacity not recorded'],
  // plancher
  [' — contreplaqué ', ' — Sperrholz ', ' — plywood '],
  [', bande de 1 m', ', 1-m-Streifen', ', 1 m strip'],
  ['résistances du contreplaqué', 'Festigkeiten des Sperrholzes', 'strengths of the plywood'],
  ['Plancher', 'Boden', 'Floor'],
  // sol et calage
  ['Réaction caractéristique', 'Charakteristische Auflagerreaktion', 'Characteristic reaction'],
  ['combinaison caractéristique (ELS)', 'charakteristische Kombination (GZG)', 'characteristic combination (SLS)'],
  ['Pression au sol sous la longrine (sol élastique)', 'Bodenpressung unter dem Kantholz (elastische Bettung)', 'Ground pressure under the sleeper (elastic ground)'],
  ['Pression au sol', 'Nachweis der Bodenpressung', 'Ground pressure'],
  ['Flexion de la plaque (porte-à-faux diagonal)', 'Nachweis Biegung der Holzplatte (diagonaler Überstand)', 'Plate bending (diagonal overhang)'],
  ['Compression transversale sous l’appui', 'Nachweis Druck rechtwinklig zur Faser', 'Compression perpendicular to the grain under the support'],
  ['Compression transversale sous l’angle', 'Druck rechtwinklig zur Faser unter der Ecke', 'Compression perpendicular to the grain under the corner'],
  ['compression transversale dépassée sous l’appui', 'Druck rechtwinklig zur Faser unter dem Auflager überschritten', 'compression perpendicular to the grain exceeded under the support'],
  ['prévoir une tôle sous les angles (compression transversale du bois)', 'Stahlblech unter den Ecken vorsehen (Querdruck im Holz)', 'provide a steel plate under the corners (compression perpendicular to the grain)'],
  ['Flexion de la tôle acier', 'Biegung des Stahlblechs', 'Steel plate bending'],
  ['élastique, pression uniforme sous la tôle', 'elastisch, gleichmäßige Pressung unter dem Blech', 'elastic, uniform pressure under the plate'],
  ['hors des épaisseurs du commerce', 'außerhalb der handelsüblichen Dicken', 'beyond commercial thicknesses'],
  ['Répartition à 45° à travers des couches continues', 'Lastausbreitung unter 45° durch durchgehende Lagen', '45° spreading through continuous layers'],
  ['hypothèse de diffusion à 45° (couches continues, rigides et bien calées)', 'Annahme einer Lastausbreitung unter 45° (durchgehende, steife, satt aufliegende Lagen)', 'assumed 45° spreading (continuous, stiff, well-bedded layers)'],
  ['hypothèse de diffusion à 45° : à valider pour le matériau des couches', 'Lastausbreitung unter 45°: für das Material der Lagen zu bestätigen', '45° spreading: to be confirmed for the layer material'],
  ['Couches continues (diffusion à 45°)', 'Durchgehende Lagen (Lastausbreitung 45°)', 'Continuous layers (45° spreading)'],
  ['épaisseur totale', 'Gesamtdicke', 'total thickness'],
  ['poutre sur appuis élastiques (Winkler), charges caractéristiques', 'elastisch gebetteter Balken (Winkler), charakteristische Lasten', 'beam on elastic supports (Winkler), characteristic loads'],
  ['max. sol élastique / pression uniforme', 'max. elastische Bettung / gleichmäßige Pressung', 'max. elastic ground / uniform pressure'],
  ['appui continu', 'durchgehende Auflagerung', 'continuous support'],
  ['Flexion de la longrine', 'Biegung des Kantholzes', 'Sleeper bending'],
  ['Cisaillement de la longrine', 'Schub im Kantholz', 'Sleeper shear'],
  ['(moyenne ', '(Mittel ', '(mean '],
  ['Charge ponctuelle admissible du support', 'Zulässige Einzellast des Untergrunds', 'Allowable point load of the support'],
  ['donnée du bâtiment', 'Angabe des Gebäudes', 'building data'],
  ['capacité du fabricant', 'Tragfähigkeit laut Hersteller', 'manufacturer capacity'],
  ['Plaques de contreplaqué F40/30', 'Sperrholzplatten F40/30', 'Plywood plates F40/30'],
  ['Plaques du stock', 'Platten aus dem Lager', 'Plates from stock'],
  ['Plaque de répartition', 'Lastverteilungsplatte', 'Spreading plate'],
  ['Plaque « ', 'Platte « ', 'Plate « '],
  ['Longrines bois C24 sous les grands côtés', 'Kanthölzer C24 unter den Längsseiten', 'C24 timber sleepers under the long sides'],
  ['sous chaque grand côté', 'unter jeder Längsseite', 'under each long side'],
  ['Tôle acier S235', 'Stahlblech S235', 'Steel plate S235'],
  ['Contreplaqué F40/30', 'Sperrholz F40/30', 'Plywood F40/30'],
  ['Contreplaqué (stock)', 'Sperrholz (Lager)', 'Plywood (stock)'],
  ['Bois C24', 'Holz C24', 'Timber C24'],
  ['aucune épaisseur courante suffisante', 'keine handelsübliche Dicke ausreichend', 'no common thickness is sufficient'],
  ['épaisseur hors des tôles courantes', 'Dicke außerhalb der üblichen Bleche', 'thickness beyond common plates'],
  ['plus grande que', 'größer als', 'larger than'],
  ['de côté', 'Seitenlänge', 'side'],
  ['hors standard', 'außerhalb Standard', 'non-standard'],
  ['flambement (', 'Knicken (', 'buckling ('],
  ['déversement (', 'Biegedrillknicken (', 'LTB ('],
  ['section (', 'Querschnitt (', 'section ('],
  ['T soudé', 'T geschweißt', 'welded T'],
  ['Acier ', 'Stahl ', 'Steel '],
  ['U plié', 'U gekantet', 'cold-formed U'],
  ['C plié', 'C gekantet', 'cold-formed C'],
  ['formé à froid', 'kaltgefertigt', 'cold-formed'],
  ['Plat ', 'Flachstahl ', 'Flat bar '],
  ['Contreplaqué F20/15', 'Sperrholz F20/15', 'Plywood F20/15'],
  ['Bois massif C24', 'Vollholz C24', 'Solid timber C24'],
  ['Lamellé-collé', 'Brettschichtholz', 'Glulam'],
  ['Solive bois', 'Holzbalken', 'Timber joist'],
  ['> portance', '> zul. Bodenpressung', '> bearing capacity'],
  ['pression ', 'Pressung ', 'pressure '],
  ['charge ', 'Last ', 'load '],
  [' mm par angle', ' mm je Ecke', ' mm per corner'],
  [' mm par groupe', ' mm je Gruppe', ' mm per group'],
  [' mm par pied central', ' mm je mittlerem Fuß', ' mm per middle foot'],
  [' cm par angle', ' cm je Ecke', ' cm per corner'],
  [' cm par groupe', ' cm je Gruppe', ' cm per group'],
  [' cm par pied central', ' cm je mittlerem Fuß', ' cm per middle foot'],
  ['sous chaque groupe', 'unter jeder Gruppe', 'under each group'],
  ['sous chaque pied', 'unter jedem Fuß', 'under each foot'],
  ['1 tôle ', '1 Blech ', '1 plate '],
  ['1 plaque ', '1 Platte ', '1 plate '],
  ['angle seul', 'einzelne Ecke', 'single corner'],
  ['pied central', 'mittlerer Fuß', 'middle foot'],
  ['Pieds centraux : surface de contact 15 × 15 cm supposée (à confirmer).', 'Mittlere Füße: Aufstandsfläche 15 × 15 cm angenommen (zu bestätigen).', 'Middle feet: contact area 15 × 15 cm assumed (to be confirmed).'],
  ['Longrines : aucune section de la liste ne suffit (6 pièces côte à côte au plus).', 'Kanthölzer: kein Querschnitt der Liste reicht aus (höchstens 6 nebeneinander).', 'Sleepers: no section of the list is sufficient (at most 6 side by side).'],
  ['Aucune solution standard pour tous les appuis : la moins mauvaise est chiffrée, une étude de répartition spécifique est nécessaire.', 'Keine Standardlösung für alle Auflager: die günstigste ist beziffert, eine gesonderte Lastverteilung ist erforderlich.', 'No standard solution for all supports: the least unfavourable one is quantified, a specific load spreading design is required.'],
  ['erf. W', 'erf. W', 'req. W'],
  ['erf. h', 'erf. h', 'req. h'],
  ['zul. σB', 'zul. σB', 'allow. σB'],
  // charges et vent
  ['Poids d’une Viewbox : modèle et pesée', 'Gewicht einer Viewbox: Modell und Wägung', 'Weight of one Viewbox: model and weighing'],
  ['G1 (barres, 78,5 kN/m³) + G2 (plafond) + G4 (sol) ≥ poids pesé, sinon complément Gc sur les rives du plancher', 'G1 (Stäbe, 78,5 kN/m³) + G2 (Decke) + G4 (Boden) ≥ gewogenes Gewicht, sonst Ergänzung Gc auf den Bodenrandträgern', 'G1 (members, 78,5 kN/m³) + G2 (ceiling) + G4 (floor) ≥ weighed weight, otherwise complement Gc on the floor edge beams'],
  [' : modèle plus lourd, pas de complément', ': Modell schwerer, keine Ergänzung', ': model heavier, no complement'],
  [' : complément Gc = ', ': Ergänzung Gc = ', ': complement Gc = '],
  ['pesée ', 'gewogen ', 'weighed '],
  ['vitesse d’arrêt d’exploitation', 'Abschaltgeschwindigkeit', 'operation stop speed'],
  ['Vent sur les côtés des Viewbox', 'Wind auf die Seiten der Viewboxen', 'Wind on the sides of the Viewbox units'],
  ['par rive (plancher et toiture)', 'je Randträger (Boden und Dach)', 'per edge beam (floor and roof)'],
  ['cp luv / lee / parallèle', 'cp Luv / Lee / parallel', 'cp windward / leeward / parallel'],
  ['Vent en service', 'Wind in Betrieb', 'Wind in service'],
  ['Vent hors service', 'Wind außer Betrieb', 'Wind out of service'],
  ['Exploitation en service', 'Verkehrslast in Betrieb', 'Imposed load in service'],
  ['Exploitation hors service', 'Verkehrslast außer Betrieb', 'Imposed load out of service'],
  ['Succion des toitures (hors service)', 'Dachsog (außer Betrieb)', 'Roof suction (out of service)'],
  ['Murs, vitrages, portes', 'Wände, Verglasungen, Türen', 'Walls, glazing, doors'],
  ['Complément de poids', 'Gewichtsergänzung', 'Weight complement'],
  ['Poids propre', 'Eigengewicht', 'Self-weight'],
  ['Plafonds', 'Decken', 'Ceilings'],
  ['Sols', 'Böden', 'Floors'],
  ['Garde-corps', 'Geländer', 'Railings'],
  ['q en service', 'q in Betrieb', 'q in service'],
  ['en service', 'in Betrieb', 'in service'],
  ['hors service', 'außer Betrieb', 'out of service'],
  ['pression saisie', 'eingegebener Druck', 'entered pressure'],
  ['qp saisi', 'qp eingegeben', 'qp entered'],
  ['zone ', 'Windzone ', 'zone '],
  ['Aucun côté exposé au vent.', 'Keine windbeanspruchte Seite.', 'No side exposed to wind.'],
  ['surface au vent seule, pas encore appliquée au calcul (vent calculé sur les côtés des Viewbox)', 'nur Windangriffsfläche, noch nicht in der Berechnung angesetzt (Wind auf den Seiten der Viewboxen)', 'wind area only, not yet applied in the analysis (wind computed on the sides of the Viewbox units)'],
  // stabilité et verdict
  ['μ requis = √(ΣRx² + ΣRy²) / ΣRz ≤ μ disponible', 'erf. μ = √(ΣRx² + ΣRy²) / ΣRz ≤ vorh. μ', 'required μ = √(ΣRx² + ΣRy²) / ΣRz ≤ available μ'],
  ['Système stable avec des appuis en compression seule (basculement vérifié dans le calcul non linéaire).', 'Das System ist mit nur druckaktiven Auflagern rechnerisch stabil (Kippsicherheit in der nichtlinearen Berechnung nachgewiesen).', 'The system is stable with compression-only supports (overturning verified in the nonlinear analysis).'],
  ['Combinaisons de stabilité non calculées.', 'Kombinationen der Lagesicherheit nicht berechnet.', 'Stability combinations not computed.'],
  ['Stabilité d’ensemble non assurée', 'Lagesicherheit nicht gegeben', 'Global stability not ensured'],
  ['et la structure devient instable (basculement)', 'und die Struktur wird instabil (Kippen)', 'and the structure becomes unstable (overturning)'],
  ['se soulève', 'hebt ab', 'lifts off'],
  ['s’ouvre', 'öffnet sich', 'opens'],
  ['l’appui ', 'das Auflager ', 'support '],
  ['le contact ', 'der Kontakt ', 'contact '],
  ['Système presque instable (mécanisme)', 'System nahezu instabil (Mechanismus)', 'System nearly unstable (mechanism)'],
  ['Système instable (mécanisme)', 'System instabil (Mechanismus)', 'Unstable system (mechanism)'],
  ['Système instable', 'System instabil', 'Unstable system'],
  ['Instabilité au 2ᵉ ordre (charge critique dépassée)', 'Instabilität nach Theorie II. Ordnung (Verzweigungslast überschritten)', 'Second-order instability (critical load exceeded)'],
  ['déplacement de', 'Verschiebung von', 'displacement of'],
  ['n’est pas tenu en', 'ist nicht gehalten in', 'is not restrained in'],
  ['n’est tenu par rien en', 'ist durch nichts gehalten in', 'is restrained by nothing in'],
  ['le nœud', 'der Knoten', 'node'],
  ['au nœud', 'am Knoten', 'at node'],
  ['nœud', 'Knoten', 'node'],
  ['Contacts indéterminés', 'Kontakte unbestimmt', 'Undetermined contacts'],
  ['Contact(s) à la limite', 'Kontakt(e) an der Grenze', 'Contact(s) at the limit'],
  ['effort résiduel', 'Restkraft', 'residual force'],
  ['négligé', 'vernachlässigt', 'neglected'],
  [' — lest ou ancrage nécessaire', ' — Ballast oder Verankerung erforderlich', ' — ballast or anchorage required'],
  [' — lest, ancrage ou frottement à justifier', ' — Ballast, Verankerung oder Reibbeiwert nachzuweisen', ' — ballast, anchorage or friction to be justified'],
  ['Glissement global', 'Globale Gleitsicherheit', 'Global sliding'],
  ['Basculement', 'Kippsicherheit', 'Overturning'],
  ['μ requis', 'erf. μ', 'required μ'],
  ['μ disponible', 'vorh. μ', 'available μ'],
  ['non calculé', 'nicht berechnet', 'not computed'],
  ['Pieds à vérins utilisés : capacité des vérins non renseignée (VBX-JACK)', 'Spindelfüße verwendet: Tragfähigkeit der Spindeln nicht erfasst (VBX-JACK)', 'Jack feet used: jack capacity not recorded (VBX-JACK)'],
  ['pas encore modélisées dans le calcul complet (escaliers, terrasses, poutres ajoutées) — verdict incomplet', 'noch nicht in der Gesamtberechnung modelliert (Treppen, Terrassen, zusätzliche Träger) — unvollständig', 'not yet modelled in the full analysis (stairs, terraces, added beams) — incomplete'],
  ['Aucune liaison horizontale entre', 'Keine horizontale Verschraubung zwischen', 'No horizontal connection between'],
  ['(perçages non alignés) : Viewbox reliées par contact seulement.', '(Bohrungen nicht fluchtend): Viewboxen nur über Kontakt verbunden.', '(drillings not aligned): units connected by contact only.'],
  ['dans le modèle (gabarit', 'im Modell (Vorlage', 'in the model (template'],
  ['replacée sur', 'aufgesetzt auf', 'placed on'],
  ['aucun angle de Viewbox sous son angle', 'keine Viewbox-Ecke unter ihrer Ecke', 'no Viewbox corner under its corner'],
  ['(empilement décalé ou appui non modélisé)', '(versetzt gestapelt oder Auflager nicht modelliert)', '(offset stack or support not modelled)'],
  ['Aucune Viewbox posée au sol : le modèle n’a pas d’appui.', 'Keine Viewbox auf dem Boden: das Modell hat kein Auflager.', 'No Viewbox on the ground: the model has no support.'],
  ['repère de la Viewbox introuvable', 'Achsensystem der Viewbox nicht gefunden', 'Viewbox frame not found'],
  // mots de liaison (en dernier)
  [' et ', ' und ', ' and '],
  [' ou ', ' oder ', ' or '],
  [' avec ', ' mit ', ' with '],
  [' sans ', ' ohne ', ' without '],
  [' entre ', ' zwischen ', ' between '],
  [' sur ', ' auf ', ' on '],
  [' sous ', ' unter ', ' under '],
  [' par ', ' je ', ' per '],
  [' de ', ' von ', ' of '],
];

const COMPILED = new Map<Lang, Array<[string | RegExp, string]>>();

function rules(lang: 'de' | 'en'): Array<[string | RegExp, string]> {
  let r = COMPILED.get(lang);
  if (!r) {
    const k = lang === 'de' ? 1 : 2;
    const phrases = [...PHRASES].sort((a, b) => String(b[0]).length - String(a[0]).length);
    r = [...PATTERNS, ...phrases].map((x) => [x[0], x[k]] as [string | RegExp, string]);
    COMPILED.set(lang, r);
  }
  return r;
}

/** Texte du moteur (français) → langue du rapport ; en français : inchangé. */
export function translate(lang: Lang, text: string): string {
  if (lang === 'fr' || !text) return text;
  let s = text.replace(/'/g, '’');
  for (const [from, to] of rules(lang)) s = typeof from === 'string' ? s.split(from).join(to) : s.replace(from, to);
  s = s.replace(/« ?/g, lang === 'de' ? '„' : '“').replace(/ ?»/g, lang === 'de' ? '“' : '”');
  s = s.replace(/ ([:;])(?=\s|$)/g, '$1');
  if (lang === 'en') s = s.replace(/(\d),(\d)/g, '$1.$2');
  return s;
}

/** Mots français qui ne doivent plus apparaître dans un rapport allemand ou anglais (contrôle des tests). */
export const FRENCH_MARKERS = [
  'rive',
  'poteau',
  'tronçon',
  'angle',
  'plancher',
  'toiture',
  'côté',
  'liaison',
  'boulon',
  'flambement',
  'déversement',
  'résistance',
  'méthode',
  'combinaison',
  'classe',
  'contreplaqué',
  'plaque',
  'réaction',
  'pression',
  'glissement',
  'basculement',
  'requis',
  'disponible',
  'vent',
  'service',
  'charge',
  'sol',
  'avec',
  'sans',
  'et',
  'ou',
  'de',
  'du',
  'des',
  'le',
  'la',
  'les',
  'par',
  'pour',
  'sur',
  'sous',
];
